#!/bin/bash
# Generated by scripts/build.sh from src/; do not edit acme-nginx.sh directly.
# acme-nginx-generated-artifact: v1
# acme-nginx-module: 00-bootstrap
export LANG=en_US.UTF-8
umask 077

ACME_VERSION="3.1.4"
ACME_ARCHIVE_SHA256="e5f8e187bbf5251e0cd8891f2622daab9850366bd17bea9f92c2fe2ee091fd32"
STATE_DIR="/etc/acme-nginx"
CONFIG_FILE="/etc/acme-nginx.conf"
ACME_HOME="$STATE_DIR/acme"
ACME_BIN="$ACME_HOME/acme.sh"
ACME_STAGE="$ACME_HOME/stage"
ACME_STAGE_CERT="$ACME_STAGE/fullchain.pem"
ACME_STAGE_KEY="$ACME_STAGE/private.key"
ACME_LIVE="$STATE_DIR/acme-live"
ACME_GENERATIONS="$ACME_LIVE/generations"
ACME_CURRENT="$ACME_LIVE/current"
ACME_CERT="$STATE_DIR/fullchain.pem"
ACME_KEY="$STATE_DIR/privkey.pem"
ACME_IDENTITY="$STATE_DIR/identity"
ACME_RELOAD="$STATE_DIR/reload.sh"
ACME_LOCK="/run/acme-nginx.lock"
ACME_RENEW_RUNNER="$STATE_DIR/renew.sh"
ACME_RENEW_STATE="$STATE_DIR/renew.state"
ACME_RELOAD_IDENTITY="# acme-nginx-reload-v1"
ACME_RENEW_IDENTITY="# acme-nginx-renew-v1"
ACME_CRON_MARKER="# acme-nginx-managed"
ACME_LOCK_FD=
ACME_LOCK_HELD=0
ACME_PRIMARY_DOMAIN=
ACME_WILDCARD_DOMAIN=
DNS_PROVIDER=cloudflare
CF_ACCOUNT_ID=
CF_TOKEN=
HUAWEICLOUD_ACCESS_KEY_ID=
HUAWEICLOUD_SECRET_ACCESS_KEY=
HUAWEICLOUD_REGION=
STAGING=0

red(){ echo -e "\033[31m\033[01m$1\033[0m";}
green(){ echo -e "\033[32m\033[01m$1\033[0m";}
yellow(){ echo -e "\033[33m\033[01m$1\033[0m";}
blue(){ echo -e "\033[36m\033[01m$1\033[0m";}
if [[ $EUID -ne 0 ]]; then
  yellow "请以root模式运行 acme-nginx"
  exit 1
fi

acme_nginx_version="v0.3.0"

valid_ipv4(){
  local ip=$1 IFS=. octets octet
  [[ $ip =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  read -r -a octets <<< "$ip"
  for octet in "${octets[@]}"; do
    ((10#$octet <= 255)) || return 1
  done
}

valid_ipv6(){
  local ip=$1 group nonempty=0
  local -a groups
  [[ -n $ip && ${#ip} -le 39 && $ip == *:* && $ip =~ ^[0-9A-Fa-f:]+$ ]] || return 1
  [[ $ip != ':' && $ip != '::' && $ip != '::1' && $ip != *:::* ]] || return 1
  [[ ! $ip =~ ^[Ff][Ee][89AaBb] && ! $ip =~ ^[Ff][CcDd] ]] || return 1
  if [[ $ip == *::* ]]; then
    [[ ${ip#*::} != *::* ]] || return 1
  fi
  IFS=':' read -r -a groups <<< "$ip"
  for group in "${groups[@]}"; do
    [[ -z $group ]] && continue
    [[ ${#group} -le 4 && $group =~ ^[0-9A-Fa-f]+$ ]] || return 1
    nonempty=$((nonempty + 1))
  done
  if [[ $ip == *::* ]]; then
    ((nonempty < 8))
  else
    ((nonempty == 8))
  fi
}

sanitize_location(){
  tr '\r\n\t' '   ' | sed 's/[[:cntrl:]]//g; s/[[:space:]][[:space:]]*/ /g; s/^ //; s/ $//' | cut -c1-160
}

valid_hostname(){
  local name=$1 label
  local -a labels
  [[ ${#name} -le 253 && $name == *.* && $name != .* && $name != *. ]] || return 1
  IFS='.' read -r -a labels <<< "$name"
  for label in "${labels[@]}"; do
    [[ ${#label} -ge 1 && ${#label} -le 63 ]] || return 1
    [[ $label =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?$ ]] || return 1
  done
}

core_dependencies_ready(){
  local cmd
  for cmd in awk bash cat chmod cmp cp curl cut date flock grep iconv jq mkdir \
    mktemp mv od openssl sed sha256sum sort tail tr uniq crontab; do
    command -v "$cmd" >/dev/null 2>&1 || return 1
  done
}

cron_daemon_is_active(){
  if command -v apk >/dev/null 2>&1; then
    rc-service crond status >/dev/null 2>&1
  else
    systemctl is-active --quiet cron 2>/dev/null ||
      systemctl is-active --quiet crond 2>/dev/null
  fi
}


prepare_state_dir(){
  local path
  for path in "$STATE_DIR" "$ACME_HOME" "$ACME_STAGE"; do
    if [[ -e $path || -L $path ]]; then
      [[ -d $path && ! -L $path ]] || return 1
    else
      mkdir -p "$path" || return 1
    fi
    chmod 700 "$path" || return 1
  done
  if [[ -e $ACME_LIVE || -L $ACME_LIVE ]]; then
    [[ -d $ACME_LIVE && ! -L $ACME_LIVE ]] || return 1
  else
    mkdir "$ACME_LIVE" || return 1
    chmod 700 "$ACME_LIVE" || return 1
  fi
  if [[ -e $ACME_GENERATIONS || -L $ACME_GENERATIONS ]]; then
    [[ -d $ACME_GENERATIONS && ! -L $ACME_GENERATIONS ]] || return 1
  else
    mkdir "$ACME_GENERATIONS" || return 1
    chmod 700 "$ACME_GENERATIONS" || return 1
  fi
}

config_mode_is_private(){
  local mode
  mode=$(stat -c '%a' "$CONFIG_FILE" 2>/dev/null || true)
  case $(uname -s 2>/dev/null) in
    MINGW*|MSYS*) return 0 ;;
    *) [[ $mode == 600 ]] ;;
  esac
}

config_is_present(){
  [[ -f $CONFIG_FILE && ! -L $CONFIG_FILE ]] || return 1
  config_mode_is_private
}

write_config_template(){
  if [[ -e $CONFIG_FILE || -L $CONFIG_FILE ]]; then
    [[ -f $CONFIG_FILE && ! -L $CONFIG_FILE ]] || return 1
    return 0
  fi
  local tmp
  tmp=$(mktemp "$STATE_DIR/.acme-nginx.conf.XXXXXX") || return 1
  if ! {
    printf '%s\n' '# acme-nginx 配置文件'
    printf '%s\n' '# DNS 供应商：cloudflare 或 huaweicloud'
    printf '%s\n' 'DNS_PROVIDER=cloudflare'
    printf '%s\n' '# --- Cloudflare 凭据（DNS_PROVIDER=cloudflare 时必填）---'
    printf '%s\n' '# Account ID 为 32 位十六进制'
    printf '%s\n' 'CF_ACCOUNT_ID='
    printf '%s\n' 'CF_TOKEN='
    printf '%s\n' '# --- 华为云凭据（DNS_PROVIDER=huaweicloud 时必填，AK/SK 模式）---'
    printf '%s\n' '# AK/SK：控制台“我的凭证”→“访问密钥”中创建'
    printf '%s\n' 'HUAWEICLOUD_ACCESS_KEY_ID='
    printf '%s\n' 'HUAWEICLOUD_SECRET_ACCESS_KEY='
    printf '%s\n' '# 区域（必填），国内建议 cn-north-4，如 cn-north-4/ap-southeast-1'
    printf '%s\n' 'HUAWEICLOUD_REGION='
    printf '%s\n' '# 联调用 Let''s Encrypt 预演服务器：1 开启，生产保持 0'
    printf '%s\n' 'STAGING=0'
    printf '%s\n' '# 主域名（必填）'
    printf '%s\n' 'DOMAIN='
    printf '%s\n' '# 是否同时申请泛域名证书：1 表示同时签 *.DOMAIN'
    printf '%s\n' 'WILDCARD=0'
  } > "$tmp" || ! chmod 600 "$tmp" || ! mv -fT -- "$tmp" "$CONFIG_FILE"; then
    rm -f "$tmp"
    return 1
  fi
}

load_config(){
  local line key value
  local provider_count=0 account_count=0 token_count=0 domain_count=0 wildcard_count=0
  local hw_ak_count=0 hw_sk_count=0 hw_region_count=0 staging_count=0
  local provider='' account='' token='' domain='' wildcard=''
  local hw_ak='' hw_sk='' hw_region='' staging=''
  [[ -f $CONFIG_FILE && ! -L $CONFIG_FILE ]] || return 1
  config_mode_is_private || return 1
  while IFS= read -r line || [[ -n $line ]]; do
    [[ -n $line ]] || continue
    [[ $line == \#* ]] && continue
    [[ $line == *=* ]] || return 1
    key=${line%%=*}
    value=${line#*=}
    [[ $value != *"'"* && $value != *$'\r'* ]] || return 1
    case $key in
      DNS_PROVIDER)
        provider_count=$((provider_count + 1))
        provider=$value
        ;;
      CF_ACCOUNT_ID)
        account_count=$((account_count + 1))
        account=$value
        ;;
      CF_TOKEN)
        token_count=$((token_count + 1))
        token=$value
        ;;
      HUAWEICLOUD_ACCESS_KEY_ID)
        hw_ak_count=$((hw_ak_count + 1))
        hw_ak=$value
        ;;
      HUAWEICLOUD_SECRET_ACCESS_KEY)
        hw_sk_count=$((hw_sk_count + 1))
        hw_sk=$value
        ;;
      HUAWEICLOUD_REGION)
        hw_region_count=$((hw_region_count + 1))
        hw_region=$value
        ;;
      STAGING)
        staging_count=$((staging_count + 1))
        staging=$value
        ;;
      DOMAIN)
        domain_count=$((domain_count + 1))
        domain=$value
        ;;
      WILDCARD)
        wildcard_count=$((wildcard_count + 1))
        wildcard=$value
        ;;
      *) return 1 ;;
    esac
  done < "$CONFIG_FILE"
  [[ $provider_count -le 1 && $account_count -le 1 && $token_count -le 1 &&
     $hw_ak_count -le 1 && $hw_sk_count -le 1 && $hw_region_count -le 1 &&
     $staging_count -le 1 && $domain_count -eq 1 && $wildcard_count -eq 1 ]] || return 1
  provider=${provider:-cloudflare}
  valid_dns_provider "$provider" || return 1
  [[ $wildcard == 0 || $wildcard == 1 ]] || return 1
  staging=${staging:-0}
  [[ $staging == 0 || $staging == 1 ]] || return 1
  normalize_acme_domain "$domain" || return 1
  DNS_PROVIDER=$provider
  CF_ACCOUNT_ID=
  CF_TOKEN=
  HUAWEICLOUD_ACCESS_KEY_ID=
  HUAWEICLOUD_SECRET_ACCESS_KEY=
  HUAWEICLOUD_REGION=
  STAGING=$staging
  if [[ $wildcard == 1 ]]; then
    ACME_WILDCARD_DOMAIN="*.$ACME_PRIMARY_DOMAIN"
  else
    ACME_WILDCARD_DOMAIN=
  fi
  case $provider in
    cloudflare)
      [[ $account_count -eq 1 && $token_count -eq 1 ]] || return 1
      valid_cloudflare_account_id "$account" || return 1
      [[ $token =~ ^[A-Za-z0-9_-]{10,200}$ ]] || return 1
      CF_ACCOUNT_ID=$account
      CF_TOKEN=$token
      ;;
    huaweicloud)
      [[ $hw_ak_count -eq 1 && $hw_sk_count -eq 1 && $hw_region_count -eq 1 ]] || return 1
      [[ -n $hw_ak && -n $hw_sk && -n $hw_region ]] || return 1
      [[ $hw_ak =~ ^[A-Za-z0-9_-]{16,64}$ ]] || return 1
      [[ $hw_sk =~ ^[A-Za-z0-9+/=_-]{16,128}$ ]] || return 1
      [[ $hw_region =~ ^[A-Za-z0-9_-]{2,32}$ ]] || return 1
      HUAWEICLOUD_ACCESS_KEY_ID=$hw_ak
      HUAWEICLOUD_SECRET_ACCESS_KEY=$hw_sk
      HUAWEICLOUD_REGION=$hw_region
      ;;
  esac
}
# acme-nginx-module: 10-acme
# Certificate functions (DNS-01 + atomic generation deployment)
certificate_san_text(){
  local cert=$1
  if openssl x509 -help 2>&1 | grep -q -- '-ext'; then
    openssl x509 -in "$cert" -noout -ext subjectAltName 2>/dev/null
  else
    openssl x509 -in "$cert" -noout -text 2>/dev/null | \
      awk '/X509v3 Subject Alternative Name/{getline; print; exit}'
  fi
}

certificate_identity_matches(){
  local cert=$1 identity=$2 san
  if valid_ipv4 "$identity" || valid_ipv6 "$identity"; then
    san=$(certificate_san_text "$cert") || return 1
    printf '%s\n' "$san" | grep -oE 'IP Address:[^,[:space:]]+' | cut -d: -f2- | grep -Fxq -- "$identity"
  elif valid_hostname "$identity"; then
    san=$(certificate_san_text "$cert") || return 1
    printf '%s\n' "$san" | grep -oE 'DNS:[^,[:space:]]+' | cut -d: -f2- | grep -Fxiq -- "$identity"
  else
    return 1
  fi
}

certificate_time_valid(){
  local cert=$1 not_before not_before_epoch now
  openssl x509 -in "$cert" -noout -checkend 0 >/dev/null 2>&1 || return 1
  not_before=$(openssl x509 -in "$cert" -noout -startdate 2>/dev/null | cut -d= -f2-) || return 1
  [[ -n $not_before ]] || return 1
  not_before_epoch=$(date -d "$not_before" +%s 2>/dev/null) || return 1
  now=$(date +%s) || return 1
  ((not_before_epoch <= now))
}

certificate_key_matches(){
  local cert=$1 key=$2 cert_public key_public
  cert_public=$(openssl x509 -in "$cert" -pubkey -noout 2>/dev/null) || return 1
  key_public=$(openssl pkey -in "$key" -pubout 2>/dev/null) || return 1
  [[ -n $cert_public && $cert_public == "$key_public" ]]
}

format_epoch_utc(){
  local epoch=$1
  [[ $epoch =~ ^[0-9]{1,12}$ ]] || return 1
  date -u -d "@$epoch" '+%Y-%m-%d %H:%M:%S UTC' 2>/dev/null
}

certificate_dns_names(){
  local cert=$1 san
  san=$(certificate_san_text "$cert") || return 1
  printf '%s\n' "$san" | grep -oE 'DNS:[^,[:space:]]+' | cut -d: -f2- |
    awk 'NF { if (result != "") result = result ", "; result = result $0 }
         END { if (result == "") exit 1; print result }'
}

load_certificate_metadata(){
  local cert=$1 key=$2 not_before not_after now remaining issuer subject
  CERT_META_NOT_BEFORE_EPOCH=
  CERT_META_NOT_AFTER_EPOCH=
  CERT_META_NOT_BEFORE=
  CERT_META_NOT_AFTER=
  CERT_META_REMAINING_DAYS=
  CERT_META_ISSUER=
  CERT_META_SUBJECT=
  CERT_META_DNS_NAMES=
  CERT_META_FINGERPRINT=
  CERT_META_KEY_MATCH=0
  CERT_META_STATE=invalid

  if [[ -L $cert || -L $key ]]; then
    [[ $cert == "${ACME_CERT:-}" && $key == "${ACME_KEY:-}" ]] || return 1
    managed_acme_live_layout_is_valid || return 1
  else
    [[ -f $cert && -f $key ]] || return 1
  fi
  openssl x509 -in "$cert" -noout >/dev/null 2>&1 || return 1
  not_before=$(openssl x509 -in "$cert" -noout -startdate 2>/dev/null | cut -d= -f2-) || return 1
  not_after=$(openssl x509 -in "$cert" -noout -enddate 2>/dev/null | cut -d= -f2-) || return 1
  CERT_META_NOT_BEFORE_EPOCH=$(date -d "$not_before" +%s 2>/dev/null) || return 1
  CERT_META_NOT_AFTER_EPOCH=$(date -d "$not_after" +%s 2>/dev/null) || return 1
  CERT_META_NOT_BEFORE=$(format_epoch_utc "$CERT_META_NOT_BEFORE_EPOCH") || return 1
  CERT_META_NOT_AFTER=$(format_epoch_utc "$CERT_META_NOT_AFTER_EPOCH") || return 1
  now=$(date +%s) || return 1
  if ((CERT_META_NOT_AFTER_EPOCH >= now)); then
    remaining=$(((CERT_META_NOT_AFTER_EPOCH - now + 86399) / 86400))
  else
    remaining=$((-((now - CERT_META_NOT_AFTER_EPOCH + 86399) / 86400)))
  fi
  CERT_META_REMAINING_DAYS=$remaining

  issuer=$(openssl x509 -in "$cert" -noout -issuer -nameopt RFC2253 2>/dev/null ||
    openssl x509 -in "$cert" -noout -issuer 2>/dev/null) || return 1
  subject=$(openssl x509 -in "$cert" -noout -subject -nameopt RFC2253 2>/dev/null ||
    openssl x509 -in "$cert" -noout -subject 2>/dev/null) || return 1
  CERT_META_ISSUER=$(printf '%s\n' "${issuer#issuer=}" | sanitize_location)
  CERT_META_SUBJECT=$(printf '%s\n' "${subject#subject=}" | sanitize_location)
  CERT_META_DNS_NAMES=$(certificate_dns_names "$cert" 2>/dev/null || true)
  CERT_META_FINGERPRINT=$(openssl x509 -in "$cert" -noout -fingerprint -sha256 2>/dev/null |
    cut -d= -f2- | tr -d '\r\n')
  [[ -n $CERT_META_ISSUER && -n $CERT_META_SUBJECT && -n $CERT_META_FINGERPRINT ]] || return 1

  if certificate_key_matches "$cert" "$key"; then
    CERT_META_KEY_MATCH=1
  fi
  if ((CERT_META_NOT_BEFORE_EPOCH > now)); then
    CERT_META_STATE=not_yet_valid
  elif ((CERT_META_NOT_AFTER_EPOCH < now)); then
    CERT_META_STATE=expired
  elif [[ $CERT_META_KEY_MATCH -ne 1 ]]; then
    CERT_META_STATE=key_mismatch
  else
    CERT_META_STATE=valid
  fi
}

managed_acme_live_layout_is_valid(){
  local current_target generation cert_target key_target
  [[ -d ${ACME_LIVE:-} && ! -L $ACME_LIVE &&
     -d ${ACME_GENERATIONS:-} && ! -L $ACME_GENERATIONS &&
     -L ${ACME_CURRENT:-} && -L ${ACME_CERT:-} && -L ${ACME_KEY:-} ]] || return 1
  [[ $(readlink "$ACME_CERT" 2>/dev/null) == 'acme-live/current/fullchain.pem' &&
     $(readlink "$ACME_KEY" 2>/dev/null) == 'acme-live/current/private.key' ]] || return 1
  current_target=$(readlink "$ACME_CURRENT" 2>/dev/null) || return 1
  [[ $current_target =~ ^generations/gen\.[A-Za-z0-9]+$ ]] || return 1
  generation="$ACME_LIVE/$current_target"
  [[ -d $generation && ! -L $generation &&
     -f $generation/fullchain.pem && ! -L $generation/fullchain.pem &&
     -f $generation/private.key && ! -L $generation/private.key ]] || return 1
  cert_target=$(readlink -f "$ACME_CERT" 2>/dev/null) || return 1
  key_target=$(readlink -f "$ACME_KEY" 2>/dev/null) || return 1
  [[ $cert_target == "$generation/fullchain.pem" &&
     $key_target == "$generation/private.key" ]]
}

acme_domain_conf_path(){
  local identity=$1
  valid_hostname "$identity" || return 1
  printf '%s/certs/%s_ecc/%s.conf\n' "$ACME_HOME" "$identity" "$identity"
}

read_acme_domain_conf_value(){
  local identity=$1 key=$2 conf prefix line value='' count=0 expected
  case "$key" in
    Le_Domain|Le_API|Le_CertCreateTime|Le_NextRenewTime|Le_InstallCertSuccessTime|\
      Le_RealCertPath|Le_RealCACertPath|Le_RealKeyPath|Le_RealFullChainPath|Le_ReloadCmd) ;;
    *) return 1 ;;
  esac
  conf=$(acme_domain_conf_path "$identity") || return 1
  [[ -f $conf && ! -L $conf ]] || return 1
  prefix="${key}='"
  while IFS= read -r line; do
    [[ $line == "$prefix"* ]] || continue
    [[ $line == *"'" ]] || return 1
    value=${line#"$prefix"}
    value=${value%"'"}
    [[ $value != *"'"* && $value != *$'\r'* ]] || return 1
    count=$((count + 1))
  done < "$conf"
  [[ $count -eq 1 ]] || return 1
  case "$key" in
    Le_Domain) valid_hostname "$value" ;;
    Le_API) [[ $value == 'https://acme-v02.api.letsencrypt.org/directory' ]] ;;
    Le_CertCreateTime|Le_NextRenewTime|Le_InstallCertSuccessTime)
      [[ $value =~ ^[0-9]{1,12}$ ]]
      ;;
    Le_RealCertPath|Le_RealCACertPath) [[ -z $value ]] ;;
    Le_RealKeyPath) [[ $value == "$ACME_STAGE_KEY" ]] ;;
    Le_RealFullChainPath) [[ $value == "$ACME_STAGE_CERT" ]] ;;
    Le_ReloadCmd)
      expected=$(printf '%s' "$ACME_RELOAD" | base64 | tr -d '\r\n') || return 1
      [[ $value == "__ACME_BASE64__START_${expected}__ACME_BASE64__END_" ]]
      ;;
  esac || return 1
  printf '%s\n' "$value"
}

acme_deployment_config_is_current(){
  local identity=$1 key
  for key in Le_RealCertPath Le_RealCACertPath Le_RealKeyPath Le_RealFullChainPath Le_ReloadCmd; do
    read_acme_domain_conf_value "$identity" "$key" >/dev/null || return 1
  done
}

load_acme_certificate_schedule(){
  local identity=$1 configured_domain
  ACME_META_CREATED_EPOCH=
  ACME_META_NEXT_RENEW_EPOCH=
  ACME_META_DEPLOYED_EPOCH=
  ACME_META_CREATED=
  ACME_META_NEXT_RENEW=
  ACME_META_DEPLOYED=
  ACME_META_CA=
  configured_domain=$(read_acme_domain_conf_value "$identity" Le_Domain) || return 1
  [[ $configured_domain == "$identity" ]] || return 1
  read_acme_domain_conf_value "$identity" Le_API >/dev/null || return 1
  ACME_META_CA="Let's Encrypt"
  ACME_META_CREATED_EPOCH=$(read_acme_domain_conf_value "$identity" Le_CertCreateTime) || return 1
  ACME_META_NEXT_RENEW_EPOCH=$(read_acme_domain_conf_value "$identity" Le_NextRenewTime) || return 1
  ACME_META_CREATED=$(format_epoch_utc "$ACME_META_CREATED_EPOCH") || return 1
  ACME_META_NEXT_RENEW=$(format_epoch_utc "$ACME_META_NEXT_RENEW_EPOCH") || return 1
  if ACME_META_DEPLOYED_EPOCH=$(read_acme_domain_conf_value "$identity" Le_InstallCertSuccessTime); then
    ACME_META_DEPLOYED=$(format_epoch_utc "$ACME_META_DEPLOYED_EPOCH") || ACME_META_DEPLOYED=
  else
    ACME_META_DEPLOYED_EPOCH=
  fi
}

dns_provider_credentials_present(){
  local account_conf="$ACME_HOME/account.conf"
  [[ -f $account_conf && ! -L $account_conf ]] || return 1
  case ${DNS_PROVIDER:-cloudflare} in
    cloudflare)
      [[ $(grep -Ec "^SAVED_CF_Token='[A-Za-z0-9_-]+'$" "$account_conf" 2>/dev/null || true) -eq 1 &&
         $(grep -Ec "^SAVED_CF_Account_ID='[0-9A-Fa-f]{32}'$" "$account_conf" 2>/dev/null || true) -eq 1 ]]
      ;;
    huaweicloud)
      [[ $(grep -Ec "^SAVED_HUAWEICLOUD_ACCESS_KEY_ID='[^']+'$" "$account_conf" 2>/dev/null || true) -eq 1 &&
         $(grep -Ec "^SAVED_HUAWEICLOUD_SECRET_ACCESS_KEY='[^']+'$" "$account_conf" 2>/dev/null || true) -eq 1 ]]
      ;;
    *) return 1 ;;
  esac
}

read_acme_identity(){
  local identity
  local -a identity_lines=()
  [[ -f $ACME_IDENTITY && ! -L $ACME_IDENTITY ]] || return 1
  mapfile -t identity_lines < "$ACME_IDENTITY" || return 1
  [[ ${#identity_lines[@]} -eq 1 ]] || return 1
  identity=${identity_lines[0]}
  valid_hostname "$identity" || return 1
  printf '%s\n' "$identity"
}

write_acme_identity(){
  local identity=$1 identity_tmp
  valid_hostname "$identity" || return 1
  identity_tmp=$(mktemp "$STATE_DIR/.acme-identity.XXXXXX") || return 1
  if ! printf '%s\n' "$identity" > "$identity_tmp" ||
     ! chmod 600 "$identity_tmp" || ! mv -fT -- "$identity_tmp" "$ACME_IDENTITY"; then
    rm -f "$identity_tmp"
    return 1
  fi
}

detect_acme_identity(){
  local identity san
  [[ -s $ACME_CERT && -s $ACME_KEY ]] || return 1
  openssl x509 -in "$ACME_CERT" -noout >/dev/null 2>&1 || return 1
  certificate_time_valid "$ACME_CERT" || return 1
  certificate_key_matches "$ACME_CERT" "$ACME_KEY" || return 1
  if identity=$(read_acme_identity 2>/dev/null); then
    if certificate_identity_matches "$ACME_CERT" "$identity"; then
      printf '%s\n' "$identity"
      return 0
    fi
  fi
  san=$(certificate_san_text "$ACME_CERT") || return 1
  identity=$(printf '%s\n' "$san" | grep -oE 'DNS:[^,[:space:]]+' | cut -d: -f2- | grep -v '^\*\.' | head -n 1)
  valid_hostname "$identity" && certificate_identity_matches "$ACME_CERT" "$identity" || return 1
  printf '%s\n' "$identity"
}

normalize_acme_domain(){
  local value=${1,,}
  value=$(printf '%s' "$value" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
  value=${value%.}
  ACME_PRIMARY_DOMAIN=
  ACME_WILDCARD_DOMAIN=
  if [[ $value == \*.* ]]; then
    ACME_PRIMARY_DOMAIN=${value#\*.}
    valid_hostname "$ACME_PRIMARY_DOMAIN" || return 1
    ACME_WILDCARD_DOMAIN="*.$ACME_PRIMARY_DOMAIN"
  elif [[ $value == *\** ]]; then
    return 1
  else
    valid_hostname "$value" || return 1
    ACME_PRIMARY_DOMAIN=$value
  fi
}

valid_cloudflare_account_id(){
  [[ $1 =~ ^[0-9A-Fa-f]{32}$ ]]
}

valid_dns_provider(){
  [[ $1 == cloudflare || $1 == huaweicloud ]]
}

dns_provider_plugin_file(){
  case ${DNS_PROVIDER:-cloudflare} in
    cloudflare) printf '%s\n' 'dns_cf.sh' ;;
    huaweicloud) printf '%s\n' 'dns_huaweicloud_aksk.sh' ;;
    *) return 1 ;;
  esac
}

write_huawei_aksk_plugin(){
  local plugin plugin_tmp
  plugin=$(dns_provider_plugin_file) || return 1
  if [[ -f $ACME_HOME/dnsapi/$plugin && ! -L $ACME_HOME/dnsapi/$plugin ]] &&
     huawei_aksk_plugin_ok; then
    return 0
  fi
  plugin_tmp=$(mktemp "$ACME_HOME/.aksk-plugin.XXXXXX") || return 1
  if ! cat > "$plugin_tmp" <<'HWAKSK'
#!/bin/sh
# acme-nginx-huaweicloud-aksk: v1
# Custom Huawei Cloud DNS dnsapi plugin for acme.sh using AK/SK signing (DNS v2 API).
# Requires: curl, openssl, jq. Uses acme.sh helpers when sourced.
export LANG=en_US.UTF-8

_hwak_sha256_hex(){
  openssl dgst -sha256 -hex | sed 's/^.*= //'
}

_hwak_hmac_hex(){
  openssl dgst -sha256 -hmac "$1" -binary | od -An -tx1 | tr -d ' \n'
}

_hwak_urlencode(){
  printf '%s' "$1" | jq -sRr @uri
}

_hwak_canonical_query(){
  printf '%s' "$1" | tr '&' '\n' | grep -v '^$' | sort | \
    awk -F= '{ if (sep) printf "&"; printf "%s=%s", $1, $2; sep=1 }'
}

_hwak_sign(){
  local method=$1 path=$2 query=$3 headers=$4 signed=$5 body=$6 sdk_date=$7
  local payload_hash canonical string2sign signature nl
  nl='
'
  case $headers in
    *"$nl") ;;
    *) headers="$headers$nl" ;;
  esac
  case $path in
    */) ;;
    *) path="$path/" ;;
  esac
  payload_hash=$(printf '%s' "$body" | _hwak_sha256_hex) || return 1
  canonical=$(printf '%s\n%s\n%s\n%s\n%s\n%s' \
    "$method" "$path" "$query" "$headers" "$signed" "$payload_hash") || return 1
  string2sign=$(printf 'SDK-HMAC-SHA256\n%s\n%s' \
    "$sdk_date" "$(printf '%s' "$canonical" | _hwak_sha256_hex)") || return 1
  signature=$(printf '%s' "$string2sign" | _hwak_hmac_hex "$HUAWEICLOUD_SECRET_ACCESS_KEY") || return 1
  printf 'SDK-HMAC-SHA256 Access=%s, SignedHeaders=%s, Signature=%s' \
    "$HUAWEICLOUD_ACCESS_KEY_ID" "$signed" "$signature"
}

_hwak_request(){
  local method=$1 path=$2 query=$3 body=$4
  local sdk_date endpoint headers signed auth url code response out canonical_query
  [ -n "$HUAWEICLOUD_ACCESS_KEY_ID" ] || return 1
  [ -n "$HUAWEICLOUD_SECRET_ACCESS_KEY" ] || return 1
  [ -n "$HUAWEICLOUD_REGION" ] || return 1
  sdk_date=$(date -u +%Y%m%dT%H%M%SZ) || return 1
  endpoint="dns.$HUAWEICLOUD_REGION.myhuaweicloud.com"
  headers=$(printf 'content-type:application/json\nhost:%s\nx-sdk-date:%s\n' "$endpoint" "$sdk_date")
  signed='content-type;host;x-sdk-date'
  canonical_query=$(_hwak_canonical_query "$query")
  url="https://$endpoint$path"
  [ -z "$canonical_query" ] || url="$url?$canonical_query"
  auth=$(_hwak_sign "$method" "$path" "$canonical_query" "$headers" "$signed" "$body" "$sdk_date") || return 1
  out=$(mktemp "${TMPDIR:-/tmp}/hwak.XXXXXX") || return 1
  if [ -n "$body" ]; then
    code=$(curl -sS -o "$out" -w '%{http_code}' -X "$method" \
      -H "Content-Type: application/json" -H "Host: $endpoint" \
      -H "X-Sdk-Date: $sdk_date" -H "Authorization: $auth" \
      --connect-timeout 10 --max-time 30 --data "$body" "$url" 2>/dev/null) || { rm -f "$out"; return 1; }
  else
    code=$(curl -sS -o "$out" -w '%{http_code}' -X "$method" \
      -H "Content-Type: application/json" -H "Host: $endpoint" \
      -H "X-Sdk-Date: $sdk_date" -H "Authorization: $auth" \
      --connect-timeout 10 --max-time 30 "$url" 2>/dev/null) || { rm -f "$out"; return 1; }
  fi
  response=$(cat "$out" 2>/dev/null)
  rm -f "$out"
  case $code in
    2??) ;;
    *) _err "huaweicloud aksk: HTTP $code $response"; return 1 ;;
  esac
  printf '%s' "$response"
}

_hwak_find_zone(){
  local fulldomain=$1 zone resp id
  zone=$fulldomain
  while :; do
    case $zone in
      *.*) zone=${zone#*.} ;;
      *) break ;;
    esac
    resp=$(_hwak_request GET "/v2/zones" "type=public&name=$(_hwak_urlencode "$zone")" "") || return 1
    id=$(printf '%s' "$resp" | jq -r --arg z "$zone" '.zones[]? | select(.name == ($z + ".")) | .id' | head -n 1)
    [ -n "$id" ] || continue
    printf '%s' "$id"
    return 0
  done
  return 1
}

_hwak_find_recordset(){
  local fulldomain=$1 resp
  resp=$(_hwak_request GET "/v2/recordsets" "type=TXT&name=$(_hwak_urlencode "$fulldomain")" "") || return 1
  printf '%s' "$resp" | jq -c --arg f "$fulldomain" '.recordsets[]? | select(.name == ($f + "."))'
}

_hwak_append_record(){
  local zone_id=$1 fulldomain=$2 txtvalue=$3 rs=$4
  local id records new_records_json body
  id=$(printf '%s' "$rs" | jq -r '.id')
  [ -n "$id" ] || return 1
  records=$(printf '%s' "$rs" | jq -r '.records[]?')
  new_records_json=$(printf '%s\n' "$records" | \
    awk -v v="\"$txtvalue\"" 'BEGIN{found=0} {if ($0==v) found=1; else print} END{if (!found) print v}' | \
    jq -Rsc 'split("\n") | map(select(length>0))')
  body=$(jq -nc --arg name "$fulldomain." --argjson records "$new_records_json" \
    '{name:$name, type:"TXT", ttl:300, records:$records}')
  _hwak_request PUT "/v2/zones/$zone_id/recordsets/$id" "" "$body" >/dev/null || return 1
}

dns_huaweicloud_aksk_add(){
  local fulldomain=$1 txtvalue=$2 zone_id rs body
  HUAWEICLOUD_ACCESS_KEY_ID="${HUAWEICLOUD_ACCESS_KEY_ID:-$(_readaccountconf_mutable HUAWEICLOUD_ACCESS_KEY_ID)}"
  HUAWEICLOUD_SECRET_ACCESS_KEY="${HUAWEICLOUD_SECRET_ACCESS_KEY:-$(_readaccountconf_mutable HUAWEICLOUD_SECRET_ACCESS_KEY)}"
  HUAWEICLOUD_REGION="${HUAWEICLOUD_REGION:-$(_readaccountconf_mutable HUAWEICLOUD_REGION)}"
  if [ -z "$HUAWEICLOUD_ACCESS_KEY_ID" ] || [ -z "$HUAWEICLOUD_SECRET_ACCESS_KEY" ] || [ -z "$HUAWEICLOUD_REGION" ]; then
    _err "Not enough information provided to dns_huaweicloud_aksk!"
    return 1
  fi
  _saveaccountconf_mutable HUAWEICLOUD_ACCESS_KEY_ID "$HUAWEICLOUD_ACCESS_KEY_ID"
  _saveaccountconf_mutable HUAWEICLOUD_SECRET_ACCESS_KEY "$HUAWEICLOUD_SECRET_ACCESS_KEY"
  _saveaccountconf_mutable HUAWEICLOUD_REGION "$HUAWEICLOUD_REGION"
  zone_id=$(_hwak_find_zone "$fulldomain") || { _err "huaweicloud aksk: cannot find zone for $fulldomain"; return 1; }
  rs=$(_hwak_find_recordset "$fulldomain") || return 1
  if [ -z "$rs" ]; then
    body=$(printf '{"name":"%s.","type":"TXT","ttl":300,"records":["\\"%s\\""]}' "$fulldomain" "$txtvalue")
    _hwak_request POST "/v2/zones/$zone_id/recordsets" "" "$body" >/dev/null || return 1
  else
    _hwak_append_record "$zone_id" "$fulldomain" "$txtvalue" "$rs" || return 1
  fi
}

dns_huaweicloud_aksk_rm(){
  local fulldomain=$1 txtvalue=$2 zone_id rs id records new_records_json body
  HUAWEICLOUD_ACCESS_KEY_ID="${HUAWEICLOUD_ACCESS_KEY_ID:-$(_readaccountconf_mutable HUAWEICLOUD_ACCESS_KEY_ID)}"
  HUAWEICLOUD_SECRET_ACCESS_KEY="${HUAWEICLOUD_SECRET_ACCESS_KEY:-$(_readaccountconf_mutable HUAWEICLOUD_SECRET_ACCESS_KEY)}"
  HUAWEICLOUD_REGION="${HUAWEICLOUD_REGION:-$(_readaccountconf_mutable HUAWEICLOUD_REGION)}"
  [ -n "$HUAWEICLOUD_ACCESS_KEY_ID" ] && [ -n "$HUAWEICLOUD_SECRET_ACCESS_KEY" ] && [ -n "$HUAWEICLOUD_REGION" ] || return 1
  zone_id=$(_hwak_find_zone "$fulldomain") || return 0
  rs=$(_hwak_find_recordset "$fulldomain") || return 0
  [ -n "$rs" ] || return 0
  id=$(printf '%s' "$rs" | jq -r '.id')
  [ -n "$id" ] || return 1
  records=$(printf '%s' "$rs" | jq -r '.records[]?')
  new_records_json=$(printf '%s\n' "$records" | awk -v v="\"$txtvalue\"" '$0 != v' | jq -Rsc 'split("\n") | map(select(length>0))')
  if [ "$new_records_json" = "[]" ]; then
    _hwak_request DELETE "/v2/zones/$zone_id/recordsets/$id" "" "" >/dev/null || return 1
  else
    body=$(jq -nc --arg name "$fulldomain." --argjson records "$new_records_json" \
      '{name:$name, type:"TXT", ttl:300, records:$records}')
    _hwak_request PUT "/v2/zones/$zone_id/recordsets/$id" "" "$body" >/dev/null || return 1
  fi
}
HWAKSK
  then
    rm -f "$plugin_tmp"
    return 1
  fi
  if ! chmod 700 "$plugin_tmp" || ! mv -fT -- "$plugin_tmp" "$ACME_HOME/dnsapi/$plugin"; then
    rm -f "$plugin_tmp"
    return 1
  fi
  huawei_aksk_plugin_ok
}

huawei_aksk_plugin_ok(){
  local plugin count
  plugin=$(dns_provider_plugin_file) || return 1
  [[ -f $ACME_HOME/dnsapi/$plugin && ! -L $ACME_HOME/dnsapi/$plugin ]] || return 1
  count=$(grep -Fxc -- '# acme-nginx-huaweicloud-aksk: v1' "$ACME_HOME/dnsapi/$plugin" 2>/dev/null || true)
  [[ $count -eq 1 ]] || return 1
  bash -n "$ACME_HOME/dnsapi/$plugin" >/dev/null 2>&1
}

install_official_acme(){
  local temp_dir archive source_dir actual_sha256 installed_version plugin
  plugin=$(dns_provider_plugin_file) || return 1
  if [[ -x $ACME_BIN ]] && \
     { [[ ${DNS_PROVIDER:-cloudflare} == huaweicloud ]] || [[ -f $ACME_HOME/dnsapi/$plugin ]]; }; then
    installed_version=$(HOME="$STATE_DIR" "$ACME_BIN" --version 2>/dev/null)
    if printf '%s\n' "$installed_version" | grep -Fxq "v$ACME_VERSION"; then
      if [[ ${DNS_PROVIDER:-cloudflare} == huaweicloud ]]; then
        write_huawei_aksk_plugin || return 1
      fi
      return 0
    fi
  fi
  temp_dir=$(mktemp -d "$STATE_DIR/.acme-install.XXXXXX") || return 1
  archive="$temp_dir/acme.sh.tar.gz"
  source_dir="$temp_dir/acme.sh-$ACME_VERSION"
  green "正在从 acme.sh 官方仓库安装 v${ACME_VERSION}……"
  if ! curl --fail --silent --show-error --location --proto '=https' --proto-redir '=https' \
      --retry 2 --connect-timeout 10 --max-time 60 -o "$archive" \
      "https://codeload.github.com/acmesh-official/acme.sh/tar.gz/refs/tags/${ACME_VERSION}"; then
    rm -rf "$temp_dir"
    red "官方 acme.sh 下载失败"
    return 1
  fi
  actual_sha256=$(sha256sum "$archive" 2>/dev/null | awk '{print $1}')
  if [[ $actual_sha256 != "$ACME_ARCHIVE_SHA256" ]]; then
    rm -rf "$temp_dir"
    red "官方 acme.sh 压缩包 SHA-256 校验失败，拒绝执行"
    return 1
  fi
  if ! tar -xzf "$archive" -C "$temp_dir" || [[ ! -f $source_dir/acme.sh ]] || \
     { [[ ${DNS_PROVIDER:-cloudflare} != huaweicloud ]] && [[ ! -f $source_dir/dnsapi/$plugin ]]; } || \
     ! (cd "$source_dir" && HOME="$STATE_DIR" bash ./acme.sh --install \
       --home "$ACME_HOME" --config-home "$ACME_HOME" --cert-home "$ACME_HOME/certs" \
       --no-cron --no-profile); then
    rm -rf "$temp_dir"
    red "官方 acme.sh 安装失败"
    return 1
  fi
  rm -rf "$temp_dir"
  installed_version=$(HOME="$STATE_DIR" "$ACME_BIN" --version 2>/dev/null)
  if [[ ! -x $ACME_BIN ]] || \
     { [[ ${DNS_PROVIDER:-cloudflare} != huaweicloud ]] && [[ ! -f $ACME_HOME/dnsapi/$plugin ]]; } || \
     ! printf '%s\n' "$installed_version" | grep -Fxq "v$ACME_VERSION"; then
    red "官方 acme.sh 安装不完整"
    return 1
  fi
  chmod 700 "$ACME_HOME" "$ACME_BIN"
  if [[ ${DNS_PROVIDER:-cloudflare} == huaweicloud ]]; then
    write_huawei_aksk_plugin || return 1
  fi
}

write_acme_reload_hook(){
  local hook_tmp
  hook_tmp=$(mktemp "$STATE_DIR/.acme_reload.XXXXXX") || return 1
  if [[ -e $ACME_RELOAD || -L $ACME_RELOAD ]] && \
     [[ ! -f $ACME_RELOAD || -L $ACME_RELOAD ]]; then
    rm -f "$hook_tmp"
    return 1
  fi
  if ! cat > "$hook_tmp" <<'ACMERELOAD'
#!/bin/bash
# Signal handlers and EXIT cleanup functions are invoked indirectly by Bash.
# shellcheck disable=SC2317,SC2329
# acme-nginx-reload-v1
export LANG=en_US.UTF-8
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
base="/etc/acme-nginx"
cert="/etc/acme-nginx/fullchain.pem"
key="/etc/acme-nginx/privkey.pem"
identity_file="/etc/acme-nginx/identity"
stage_cert=
stage_key=
new_generation=
old_current_target=
deployment_started=0
created_layout=0
restore_managed_links=0

cleanup_deploy_files(){
  [[ -z $stage_cert ]] || rm -f -- "$stage_cert"
  [[ -z $stage_key ]] || rm -f -- "$stage_key"
}

switch_current(){
  local target=$1 pointer_tmp
  [[ $target =~ ^generations/gen\.[A-Za-z0-9]+$ ]] || return 1
  pointer_tmp=$(mktemp "$base/acme-live/.current.XXXXXX") || return 1
  rm -f -- "$pointer_tmp" || return 1
  if ! ln -s -- "$target" "$pointer_tmp" ||
     ! mv -Tf -- "$pointer_tmp" "$base/acme-live/current"; then
    rm -f -- "$pointer_tmp"
    return 1
  fi
}

install_managed_link(){
  local destination=$1 target=$2 link_tmp
  link_tmp=$(mktemp "$base/.acme-link.XXXXXX") || return 1
  rm -f -- "$link_tmp" || return 1
  if ! ln -s -- "$target" "$link_tmp" || ! mv -Tf -- "$link_tmp" "$destination"; then
    rm -f -- "$link_tmp"
    return 1
  fi
}

rollback_deployment(){
  local failed=0 pointer_released=0 new_target current_after
  [[ $deployment_started -eq 1 ]] || return 0
  if [[ -n $old_current_target ]]; then
    if switch_current "$old_current_target"; then
      pointer_released=1
    else
      failed=1
    fi
  elif [[ $created_layout -eq 1 ]]; then
    if rm -f -- "$cert" "$key" "$base/acme-live/current"; then
      pointer_released=1
    else
      failed=1
    fi
  fi
  if [[ $restore_managed_links -eq 1 && -n $old_current_target ]]; then
    install_managed_link "$cert" 'acme-live/current/fullchain.pem' || failed=1
    install_managed_link "$key" 'acme-live/current/private.key' || failed=1
    if [[ ! -L $cert || ! -L $key ]] ||
       [[ $(readlink "$cert" 2>/dev/null) != 'acme-live/current/fullchain.pem' ]] ||
       [[ $(readlink "$key" 2>/dev/null) != 'acme-live/current/private.key' ]]; then
      failed=1
    fi
  fi
  if [[ -n $new_generation ]]; then
    new_target="generations/${new_generation##*/}"
    current_after=$(readlink "$base/acme-live/current" 2>/dev/null || true)
    [[ $current_after != "$new_target" ]] && pointer_released=1
  fi
  if [[ $pointer_released -eq 1 && -n $new_generation ]]; then
    rm -rf -- "$new_generation" || failed=1
  fi
  [[ $failed -eq 0 ]] || return 1
  deployment_started=0
  restore_managed_links=0
}

commit_deployment(){
  local current_target generation
  deployment_started=0
  current_target=$(readlink "$base/acme-live/current" 2>/dev/null || true)
  [[ $current_target =~ ^generations/gen\.[A-Za-z0-9]+$ ]] || return 0
  for generation in "$base/acme-live/generations"/gen.*; do
    [[ -e $generation || -L $generation ]] || continue
    [[ $generation == "$base/acme-live/$current_target" ]] && continue
    [[ -d $generation && ! -L $generation && ${generation##*/} =~ ^gen\.[A-Za-z0-9]+$ ]] || continue
    rm -rf -- "$generation" || true
  done
}

handle_deploy_signal(){
  trap '' HUP INT TERM
  rollback_deployment || true
  exit 1
}

nginx_service_active(){
  if command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]; then
    systemctl is-active --quiet nginx
  elif command -v rc-service >/dev/null 2>&1; then
    rc-service nginx status >/dev/null 2>&1
  else
    return 1
  fi
}

reload_nginx(){
  if command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]; then
    systemctl reload nginx >/dev/null 2>&1
  elif command -v rc-service >/dev/null 2>&1; then
    rc-service nginx reload >/dev/null 2>&1
  else
    return 1
  fi
}

trap cleanup_deploy_files EXIT
trap handle_deploy_signal HUP INT TERM
[[ -d $base && ! -L $base && -f $identity_file && ! -L $identity_file ]] || exit 1
mapfile -t identity_lines < "$identity_file" || exit 1
[[ ${#identity_lines[@]} -eq 1 ]] || exit 1
identity=${identity_lines[0]}
[[ ${#identity} -le 253 && $identity == *.* && $identity != *..* &&
   $identity =~ ^[A-Za-z0-9][A-Za-z0-9.-]*[A-Za-z0-9]$ ]] || exit 1
IFS=. read -r -a identity_labels <<< "$identity"
for label in "${identity_labels[@]}"; do
  [[ ${#label} -le 63 && $label != -* && $label != *- ]] || exit 1
done
source_dir="$base/acme/stage"
source_cert="$source_dir/fullchain.pem"
source_key="$source_dir/private.key"
[[ -d $base/acme && ! -L $base/acme && -d $source_dir && ! -L $source_dir &&
   -f $source_cert && ! -L $source_cert && -f $source_key && ! -L $source_key ]] || exit 1
stage_cert=$(mktemp "$base/.acme-cert.deploy.XXXXXX") || exit 1
stage_key=$(mktemp "$base/.acme-key.deploy.XXXXXX") || exit 1
if ! cp -- "$source_cert" "$stage_cert" || ! cp -- "$source_key" "$stage_key" ||
   ! chmod 600 "$stage_cert" "$stage_key"; then
  exit 1
fi
openssl x509 -in "$stage_cert" -noout -checkend 0 >/dev/null 2>&1 || exit 1
not_before=$(openssl x509 -in "$stage_cert" -noout -startdate 2>/dev/null | cut -d= -f2-) || exit 1
not_before_epoch=$(date -d "$not_before" +%s 2>/dev/null) || exit 1
[[ $not_before_epoch -le $(date +%s) ]] || exit 1
if openssl x509 -help 2>&1 | grep -q -- '-ext'; then
  san=$(openssl x509 -in "$stage_cert" -noout -ext subjectAltName 2>/dev/null) || exit 1
else
  san=$(openssl x509 -in "$stage_cert" -noout -text 2>/dev/null | awk '/X509v3 Subject Alternative Name/{getline; print; exit}') || exit 1
fi
printf '%s\n' "$san" | grep -oE 'DNS:[^,[:space:]]+' | cut -d: -f2- | grep -Fxiq -- "$identity" || exit 1
cert_public=$(openssl x509 -in "$stage_cert" -pubkey -noout 2>/dev/null) || exit 1
key_public=$(openssl pkey -in "$stage_key" -pubout 2>/dev/null) || exit 1
[[ -n "$cert_public" && "$cert_public" == "$key_public" ]] || exit 1
if [[ -e $base/acme-live || -L $base/acme-live ]]; then
  [[ -d $base/acme-live && ! -L $base/acme-live ]] || exit 1
else
  mkdir "$base/acme-live" || exit 1
  chmod 700 "$base/acme-live" || exit 1
fi
if [[ -e $base/acme-live/generations || -L $base/acme-live/generations ]]; then
  [[ -d $base/acme-live/generations && ! -L $base/acme-live/generations ]] || exit 1
else
  mkdir "$base/acme-live/generations" || exit 1
  chmod 700 "$base/acme-live/generations" || exit 1
fi
new_generation=$(mktemp -d "$base/acme-live/generations/gen.XXXXXX") || exit 1
chmod 700 "$new_generation" || exit 1
deployment_started=1
if ! mv -fT -- "$stage_cert" "$new_generation/fullchain.pem" ||
   ! mv -fT -- "$stage_key" "$new_generation/private.key" ||
   ! chmod 600 "$new_generation/fullchain.pem" "$new_generation/private.key"; then
  rollback_deployment || true
  exit 1
fi
stage_cert=
stage_key=

current_valid=0
if [[ -e $base/acme-live/current || -L $base/acme-live/current ]]; then
  [[ -L $base/acme-live/current ]] || { rollback_deployment || true; exit 1; }
  current_target=$(readlink "$base/acme-live/current" 2>/dev/null) || {
    rollback_deployment || true
    exit 1
  }
  if [[ $current_target =~ ^generations/gen\.[A-Za-z0-9]+$ &&
        -d $base/acme-live/$current_target && ! -L $base/acme-live/$current_target &&
        -f $base/acme-live/$current_target/fullchain.pem &&
        ! -L $base/acme-live/$current_target/fullchain.pem &&
        -f $base/acme-live/$current_target/private.key &&
        ! -L $base/acme-live/$current_target/private.key ]]; then
    current_public=$(openssl x509 -in "$base/acme-live/$current_target/fullchain.pem" \
      -pubkey -noout 2>/dev/null) || current_public=
    current_key_public=$(openssl pkey -in "$base/acme-live/$current_target/private.key" \
      -pubout 2>/dev/null) || current_key_public=
    if [[ -n $current_public && $current_public == "$current_key_public" ]]; then
      current_valid=1
    fi
  fi
  [[ $current_valid -eq 1 ]] || { rollback_deployment || true; exit 1; }
fi

cert_exists=0
key_exists=0
cert_managed=0
key_managed=0
[[ -e $cert || -L $cert ]] && cert_exists=1
[[ -e $key || -L $key ]] && key_exists=1
if [[ -L $cert ]]; then
  [[ $(readlink "$cert" 2>/dev/null) == 'acme-live/current/fullchain.pem' ]] || {
    rollback_deployment || true
    exit 1
  }
  cert_managed=1
elif [[ $cert_exists -eq 1 && ! -f $cert ]]; then
  rollback_deployment || true
  exit 1
fi
if [[ -L $key ]]; then
  [[ $(readlink "$key" 2>/dev/null) == 'acme-live/current/private.key' ]] || {
    rollback_deployment || true
    exit 1
  }
  key_managed=1
elif [[ $key_exists -eq 1 && ! -f $key ]]; then
  rollback_deployment || true
  exit 1
fi

if [[ $cert_exists -eq 1 && $key_exists -eq 1 ]]; then
  old_cert_public=$(openssl x509 -in "$cert" -pubkey -noout 2>/dev/null) || old_cert_public=
  old_key_public=$(openssl pkey -in "$key" -pubout 2>/dev/null) || old_key_public=
  [[ -n $old_cert_public && $old_cert_public == "$old_key_public" ]] || {
    rollback_deployment || true
    exit 1
  }
  if [[ $cert_managed -eq 0 && $key_managed -eq 0 ]]; then
    preserved_generation=$(mktemp -d "$base/acme-live/generations/gen.XXXXXX") || {
      rollback_deployment || true
      exit 1
    }
    if ! chmod 700 "$preserved_generation" ||
       ! cp -- "$cert" "$preserved_generation/fullchain.pem" ||
       ! cp -- "$key" "$preserved_generation/private.key" ||
       ! chmod 600 "$preserved_generation/fullchain.pem" "$preserved_generation/private.key"; then
      rm -rf -- "$preserved_generation"
      rollback_deployment || true
      exit 1
    fi
    old_current_target="generations/${preserved_generation##*/}"
    switch_current "$old_current_target" || {
      rm -rf -- "$preserved_generation"
      rollback_deployment || true
      exit 1
    }
  else
    [[ $current_valid -eq 1 ]] || { rollback_deployment || true; exit 1; }
    old_current_target=$current_target
  fi
  if [[ $cert_managed -eq 0 || $key_managed -eq 0 ]]; then
    restore_managed_links=1
  fi
  if [[ $cert_managed -eq 0 ]] &&
     ! install_managed_link "$cert" 'acme-live/current/fullchain.pem'; then
    rollback_deployment || true
    exit 1
  fi
  if [[ $key_managed -eq 0 ]] &&
     ! install_managed_link "$key" 'acme-live/current/private.key'; then
    rollback_deployment || true
    exit 1
  fi
  switch_current "generations/${new_generation##*/}" || {
    rollback_deployment || true
    exit 1
  }
elif [[ $cert_exists -eq 0 && $key_exists -eq 0 ]]; then
  created_layout=1
  switch_current "generations/${new_generation##*/}" || {
    rollback_deployment || true
    exit 1
  }
  install_managed_link "$cert" 'acme-live/current/fullchain.pem' || {
    rollback_deployment || true
    exit 1
  }
  install_managed_link "$key" 'acme-live/current/private.key' || {
    rollback_deployment || true
    exit 1
  }
else
  rollback_deployment || true
  exit 1
fi

if ! nginx_service_active; then
  commit_deployment
  exit 0
fi
if reload_nginx; then
  commit_deployment
  exit 0
fi
rollback_deployment || true
exit 1
ACMERELOAD
  then
    rm -f "$hook_tmp"
    return 1
  fi
  if ! chmod 700 "$hook_tmp" || ! mv -fT -- "$hook_tmp" "$ACME_RELOAD"; then
    rm -f "$hook_tmp"
    return 1
  fi
  acme_reload_hook_is_current
}

acme_reload_hook_is_current(){
  # Dollar-prefixed names in the grep patterns are literal generated-hook text.
  # shellcheck disable=SC2016
  [[ -f $ACME_RELOAD && ! -L $ACME_RELOAD && -x $ACME_RELOAD ]] &&
    [[ $(grep -Fxc "$ACME_RELOAD_IDENTITY" "$ACME_RELOAD" 2>/dev/null || true) -eq 1 ]] &&
    grep -Fqx 'base="/etc/acme-nginx"' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx 'cert="/etc/acme-nginx/fullchain.pem"' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx 'key="/etc/acme-nginx/privkey.pem"' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx 'identity_file="/etc/acme-nginx/identity"' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx 'source_dir="$base/acme/stage"' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx 'source_cert="$source_dir/fullchain.pem"' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx 'source_key="$source_dir/private.key"' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx 'deployment_started=1' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx '    restore_managed_links=1' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx 'if reload_nginx; then' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx '  commit_deployment' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx '  exit 0' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx 'rollback_deployment || true' "$ACME_RELOAD" 2>/dev/null &&
    grep -Fqx 'exit 1' "$ACME_RELOAD" 2>/dev/null &&
    bash -n "$ACME_RELOAD" >/dev/null 2>&1
}

prepare_acme_deploy_stage(){
  local path
  if [[ -e $ACME_STAGE || -L $ACME_STAGE ]]; then
    [[ -d $ACME_STAGE && ! -L $ACME_STAGE ]] || return 1
  else
    mkdir "$ACME_STAGE" || return 1
  fi
  chmod 700 "$ACME_STAGE" || return 1
  for path in "$ACME_STAGE_CERT" "$ACME_STAGE_KEY"; do
    [[ -e $path || -L $path ]] || continue
    [[ -f $path && ! -L $path ]] || return 1
  done
}

valid_acme_renewal_identity(){
  local identity plugin
  plugin=$(dns_provider_plugin_file) || return 1
  [[ -x $ACME_BIN && -f $ACME_HOME/dnsapi/$plugin ]] || return 1
  identity=$(read_acme_identity 2>/dev/null) || return 1
  if ! load_certificate_metadata "$ACME_CERT" "$ACME_KEY" ||
     [[ $CERT_META_STATE != valid ]] ||
     ! certificate_identity_matches "$ACME_CERT" "$identity" ||
     ! load_acme_certificate_schedule "$identity"; then
    return 1
  fi
  printf '%s\n' "$identity"
}

recover_acme_renewal_identity(){
  local identity
  identity=$(detect_acme_identity 2>/dev/null) || return 1
  load_acme_certificate_schedule "$identity" || return 1
  write_acme_identity "$identity" || return 1
  printf '%s\n' "$identity"
}

register_acme_certificate_deployment(){
  local identity=$1 initial_install=${2:-0}
  [[ $initial_install == 0 || $initial_install == 1 ]] || return 1
  valid_hostname "$identity" || return 1
  acme_reload_hook_is_current || return 1
  prepare_acme_deploy_stage || return 1
  if ! HOME="$STATE_DIR" "$ACME_BIN" \
      --home "$ACME_HOME" --config-home "$ACME_HOME" \
      --install-cert -d "$identity" --ecc \
      --key-file "$ACME_STAGE_KEY" --fullchain-file "$ACME_STAGE_CERT" \
      --reloadcmd "$ACME_RELOAD"; then
    return 1
  fi
  managed_acme_live_layout_is_valid &&
    acme_deployment_config_is_current "$identity" &&
    load_certificate_metadata "$ACME_CERT" "$ACME_KEY" &&
    [[ $CERT_META_STATE == valid ]] &&
    certificate_identity_matches "$ACME_CERT" "$identity"
}

issue_certificate(){
  local -a issue_args
  local provider plugin
  provider=${DNS_PROVIDER:-cloudflare}
  [[ -n ${ACME_PRIMARY_DOMAIN:-} ]] || return 1
  valid_dns_provider "$provider" || return 1
  case $provider in
    cloudflare)
      [[ -n ${CF_TOKEN:-} && -n ${CF_ACCOUNT_ID:-} ]] || return 1
      valid_cloudflare_account_id "$CF_ACCOUNT_ID" || return 1
      [[ $CF_TOKEN =~ ^[A-Za-z0-9_-]{10,200}$ ]] || return 1
      ;;
    huaweicloud)
      [[ -n ${HUAWEICLOUD_ACCESS_KEY_ID:-} && -n ${HUAWEICLOUD_SECRET_ACCESS_KEY:-} &&
         -n ${HUAWEICLOUD_REGION:-} ]] || return 1
      ;;
  esac
  plugin=$(dns_provider_plugin_file) || return 1
  install_official_acme || return 1
  write_acme_reload_hook || return 1
  issue_args=(--home "$ACME_HOME" --config-home "$ACME_HOME" --issue \
    --dns "${plugin%.sh}" --keylength ec-256 -d "$ACME_PRIMARY_DOMAIN")
  if [[ ${STAGING:-0} == 1 ]]; then
    issue_args+=(--server https://acme-staging-v02.api.letsencrypt.org/directory)
  else
    issue_args+=(--server letsencrypt)
  fi
  if [[ -n ${ACME_WILDCARD_DOMAIN:-} ]]; then
    issue_args+=(-d "$ACME_WILDCARD_DOMAIN")
    blue "将申请：$ACME_PRIMARY_DOMAIN + $ACME_WILDCARD_DOMAIN"
  else
    blue "将申请单域名证书：$ACME_PRIMARY_DOMAIN"
  fi
  case $provider in
    cloudflare)
      if ! HOME="$STATE_DIR" CF_Token="$CF_TOKEN" CF_Account_ID="$CF_ACCOUNT_ID" \
          CF_Zone_ID='' CF_Key='' CF_Email='' \
          "$ACME_BIN" "${issue_args[@]}"; then
        red "Cloudflare DNS 验证或证书签发失败"
        return 1
      fi
      ;;
    huaweicloud)
      if ! HOME="$STATE_DIR" HUAWEICLOUD_ACCESS_KEY_ID="$HUAWEICLOUD_ACCESS_KEY_ID" \
          HUAWEICLOUD_SECRET_ACCESS_KEY="$HUAWEICLOUD_SECRET_ACCESS_KEY" \
          HUAWEICLOUD_REGION="$HUAWEICLOUD_REGION" \
          "$ACME_BIN" "${issue_args[@]}"; then
        red "华为云 DNS 验证或证书签发失败"
        return 1
      fi
      ;;
  esac
  if ! write_acme_identity "$ACME_PRIMARY_DOMAIN"; then
    red "写入 ACME 身份失败"
    return 1
  fi
  if ! register_acme_certificate_deployment "$ACME_PRIMARY_DOMAIN" 0; then
    red "证书签发成功，但部署到 $STATE_DIR 失败"
    return 1
  fi
  green "DNS API 证书申请完成（${provider}）"
}

show_certificate_metadata(){
  local label=$1 cert=$2 key=$3 identity=${4:-}
  green "证书类型: $label"
  if ! load_certificate_metadata "$cert" "$key"; then
    red "证书状态: 无法读取或文件不完整"
    return 1
  fi
  case $CERT_META_STATE in
    valid) green "证书状态: 有效" ;;
    expired) red "证书状态: 已过期" ;;
    not_yet_valid) red "证书状态: 尚未生效" ;;
    key_mismatch) red "证书状态: 证书与私钥不匹配" ;;
    *) red "证书状态: 无效" ;;
  esac
  printf '覆盖域名: %s\n' "${CERT_META_DNS_NAMES:-未提供 SAN}"
  printf '签发机构: %s\n' "$CERT_META_ISSUER"
  printf '生效时间: %s\n' "$CERT_META_NOT_BEFORE"
  printf '到期时间: %s\n' "$CERT_META_NOT_AFTER"
  if ((CERT_META_REMAINING_DAYS < 0)); then
    red "剩余有效期: 已过期 $((-CERT_META_REMAINING_DAYS)) 天"
  elif ((CERT_META_REMAINING_DAYS <= 30)); then
    yellow "剩余有效期: ${CERT_META_REMAINING_DAYS} 天"
  else
    green "剩余有效期: ${CERT_META_REMAINING_DAYS} 天"
  fi
  if [[ $CERT_META_KEY_MATCH -eq 1 ]]; then
    green "证书/私钥: 匹配"
  else
    red "证书/私钥: 不匹配"
  fi
  if [[ -n $identity ]]; then
    if certificate_identity_matches "$cert" "$identity"; then
      green "TLS 身份: $identity（证书已覆盖）"
    else
      red "TLS 身份: $identity（证书未覆盖）"
    fi
  fi
  printf 'SHA-256 指纹: %s\n' "$CERT_META_FINGERPRINT"
}

show_acme_certificate_schedule(){
  local identity=$1
  if load_acme_certificate_schedule "$identity"; then
    printf 'ACME 服务: %s\n' "$ACME_META_CA"
    printf '最近签发/续期: %s\n' "$ACME_META_CREATED"
    printf '当前计划续期: %s\n' "$ACME_META_NEXT_RENEW"
    printf '最近部署成功: %s\n' "${ACME_META_DEPLOYED:-暂无记录}"
  else
    yellow "ACME 时间记录: 无法安全读取"
    return 1
  fi
}
# acme-nginx-module: 60-cron
# Manage only acme-nginx-owned crontab entries.
load_current_crontab(){
  local error_file error_text temp_base=$STATE_DIR
  CURRENT_CRONTAB=
  [[ -d $temp_base ]] || temp_base=/tmp
  error_file=$(mktemp "$temp_base/.crontab-error.XXXXXX") || return 1
  if CURRENT_CRONTAB=$(crontab -l 2>"$error_file"); then
    rm -f "$error_file"
    return 0
  fi
  error_text=$(cat "$error_file" 2>/dev/null)
  rm -f "$error_file"
  if printf '%s\n' "$error_text" | grep -qi 'no crontab for'; then
    return 0
  fi
  if printf '%s\n' "$error_text" | grep -qi 'no such file or directory' && \
     [[ ! -e /var/spool/cron/crontabs/root && ! -e /var/spool/cron/root ]]; then
    return 0
  fi
  red "读取root crontab失败，拒绝覆盖现有定时任务"
  return 1
}

acme_lock_path(){
  printf '%s\n' "${ACME_LOCK:-$STATE_DIR/acme.lock}"
}

release_acme_lock(){
  local failed=0
  if [[ ${ACME_LOCK_FD:-} =~ ^[0-9]+$ ]]; then
    flock -u "$ACME_LOCK_FD" || failed=1
    if ! exec {ACME_LOCK_FD}>&-; then
      failed=1
    fi
    ACME_LOCK_FD=
  fi
  ACME_LOCK_HELD=0
  return "$failed"
}

acquire_acme_lock(){
  local lock path
  [[ ${ACME_LOCK_HELD:-0} -eq 1 ]] && return 0
  lock=$(acme_lock_path)
  [[ -d $STATE_DIR && ! -L $STATE_DIR ]] || return 1
  if [[ -e $lock || -L $lock ]]; then
    [[ -f $lock && ! -L $lock ]] || return 1
  fi
  ACME_LOCK_FD=
  exec {ACME_LOCK_FD}> "$lock" || return 1
  if ! chmod 600 "$lock" || ! flock -w 30 "$ACME_LOCK_FD"; then
    release_acme_lock >/dev/null 2>&1 || true
    return 1
  fi
  ACME_LOCK_HELD=1
}

with_acme_lock(){
  local owned=0 status
  if [[ ${ACME_LOCK_HELD:-0} -ne 1 ]]; then
    acquire_acme_lock || {
      red "另一个证书或续期操作正在执行，请稍后重试"
      return 1
    }
    owned=1
  fi
  if "$@"; then status=0; else status=$?; fi
  if [[ $owned -eq 1 ]] && ! release_acme_lock; then
    red "释放 ACME 操作锁失败"
    [[ $status -ne 0 ]] || status=1
  fi
  return "$status"
}

acme_renew_runner_path(){
  printf '%s\n' "${ACME_RENEW_RUNNER:-$STATE_DIR/renew.sh}"
}

acme_renew_state_path(){
  printf '%s\n' "${ACME_RENEW_STATE:-$STATE_DIR/renew.state}"
}

acme_renew_runner_identity(){
  printf '%s\n' "${ACME_RENEW_IDENTITY:-# acme-nginx-renew-v1}"
}

# Parsed values are consumed by the certificate management module.
# shellcheck disable=SC2034
load_acme_renew_state(){
  local state line key value mode
  local check_epoch='' result='' exit_code='' renewal_epoch='' fingerprint=''
  local check_count=0 result_count=0 exit_count=0 renewal_count=0 fingerprint_count=0
  ACME_RENEW_LAST_CHECK_EPOCH=
  ACME_RENEW_LAST_CHECK=
  ACME_RENEW_LAST_RESULT=
  ACME_RENEW_LAST_EXIT_CODE=
  ACME_RENEW_LAST_RENEWAL_EPOCH=
  ACME_RENEW_LAST_RENEWAL=
  ACME_RENEW_FINGERPRINT=
  state=$(acme_renew_state_path)
  [[ -f $state && ! -L $state ]] || return 1
  mode=$(stat -c '%a' "$state" 2>/dev/null || true)
  case $(uname -s 2>/dev/null) in
    MINGW*|MSYS*) ;;
    *) [[ $mode == 600 ]] || return 1 ;;
  esac
  while IFS= read -r line || [[ -n $line ]]; do
    [[ $line == *=* ]] || return 1
    key=${line%%=*}
    value=${line#*=}
    case $key in
      last_check_epoch)
        check_count=$((check_count + 1))
        check_epoch=$value
        ;;
      last_result)
        result_count=$((result_count + 1))
        result=$value
        ;;
      last_exit_code)
        exit_count=$((exit_count + 1))
        exit_code=$value
        ;;
      last_renewal_epoch)
        renewal_count=$((renewal_count + 1))
        renewal_epoch=$value
        ;;
      cert_fingerprint)
        fingerprint_count=$((fingerprint_count + 1))
        fingerprint=$value
        ;;
      *) return 1 ;;
    esac
  done < "$state"
  [[ $check_count -eq 1 && $result_count -eq 1 && $exit_count -eq 1 &&
     $renewal_count -eq 1 && $fingerprint_count -eq 1 ]] || return 1
  [[ $check_epoch =~ ^[1-9][0-9]{0,11}$ ]] || return 1
  [[ $result == renewed || $result == unchanged || $result == failed ]] || return 1
  [[ $exit_code =~ ^(0|[1-9][0-9]{0,2})$ ]] && ((exit_code <= 255)) || return 1
  [[ $renewal_epoch =~ ^(0|[1-9][0-9]{0,11})$ ]] &&
    ((renewal_epoch <= check_epoch)) || return 1
  [[ -z $fingerprint || $fingerprint =~ ^[0-9a-f]{64}$ ]] || return 1
  if [[ $result != failed ]]; then
    [[ $exit_code -eq 0 && -n $fingerprint ]] || return 1
  else
    [[ $exit_code -ne 0 ]] || return 1
  fi
  [[ $result != renewed || $renewal_epoch -eq $check_epoch ]] || return 1
  ACME_RENEW_LAST_CHECK=$(format_epoch_utc "$check_epoch") || return 1
  if [[ $renewal_epoch -ne 0 ]]; then
    ACME_RENEW_LAST_RENEWAL=$(format_epoch_utc "$renewal_epoch") || return 1
  fi
  ACME_RENEW_LAST_CHECK_EPOCH=$check_epoch
  ACME_RENEW_LAST_RESULT=$result
  ACME_RENEW_LAST_EXIT_CODE=$exit_code
  ACME_RENEW_LAST_RENEWAL_EPOCH=$renewal_epoch
  ACME_RENEW_FINGERPRINT=$fingerprint
}

crontab_has_acme_entries(){
  local content=$1 runner
  runner=$(acme_renew_runner_path)
  printf '%s\n' "$content" | grep -Fq "$ACME_CRON_MARKER" ||
    printf '%s\n' "$content" | grep -Fq "$ACME_BIN --cron" ||
    printf '%s\n' "$content" | grep -Fq "$runner"
}

acme_renew_cron_entry(){
  local runner
  runner=$(acme_renew_runner_path)
  printf '%s\n' "17 3,9,15,21 * * * $runner > /dev/null 2>&1 $ACME_CRON_MARKER"
}

acme_renew_cron_is_current(){
  local content=$1 entry runner exact_count marker_count runner_count direct_count
  entry=$(acme_renew_cron_entry)
  runner=$(acme_renew_runner_path)
  exact_count=$(printf '%s\n' "$content" | grep -Fxc -- "$entry" || true)
  marker_count=$(printf '%s\n' "$content" | grep -Fc -- "$ACME_CRON_MARKER" || true)
  runner_count=$(printf '%s\n' "$content" | grep -Fc -- "$runner" || true)
  direct_count=$(printf '%s\n' "$content" | grep -Fc -- "$ACME_BIN --cron" || true)
  [[ $exact_count -eq 1 && $marker_count -eq 1 && $runner_count -eq 1 && $direct_count -eq 0 ]]
}

filter_acme_cron_entries(){
  local runner
  runner=$(acme_renew_runner_path)
  grep -Fv "$ACME_CRON_MARKER" |
    grep -Fv "$ACME_BIN --cron" |
    grep -Fv "$runner"
}

acme_renew_runner_is_current(){
  local runner identity mode expected_cron_command expected_force_command expected_state_dir
  local expected_acme_bin expected_acme_home expected_cert_file expected_state_file
  local expected_identity_file expected_lock_file
  runner=$(acme_renew_runner_path)
  identity=$(acme_renew_runner_identity)
  expected_cron_command="  HOME=\"\$state_dir\" \"\$acme_bin\" --cron --home \"\$acme_home\" --config-home \"\$acme_home\""
  expected_force_command="  HOME=\"\$state_dir\" \"\$acme_bin\" --home \"\$acme_home\" --config-home \"\$acme_home\" --renew -d \"\$acme_identity\" --ecc --force"
  printf -v expected_state_dir 'state_dir=%q' "$STATE_DIR"
  printf -v expected_acme_bin 'acme_bin=%q' "$ACME_BIN"
  printf -v expected_acme_home 'acme_home=%q' "$ACME_HOME"
  printf -v expected_cert_file 'cert_file=%q' "${ACME_CERT:-$STATE_DIR/fullchain.pem}"
  printf -v expected_state_file 'state_file=%q' "$(acme_renew_state_path)"
  printf -v expected_identity_file 'identity_file=%q' "$ACME_IDENTITY"
  printf -v expected_lock_file 'lock_file=%q' "$(acme_lock_path)"
  [[ -f $runner && ! -L $runner && -x $runner ]] || return 1
  mode=$(stat -c '%a' "$runner" 2>/dev/null || true)
  case $(uname -s 2>/dev/null) in
    MINGW*|MSYS*) ;;
    *) [[ $mode == 700 ]] || return 1 ;;
  esac
  # Dollar-prefixed names below are literal generated-runner text.
  # shellcheck disable=SC2016
  [[ $(grep -Fxc -- "$identity" "$runner" 2>/dev/null || true) -eq 1 ]] &&
    grep -Fqx -- "$expected_state_dir" "$runner" 2>/dev/null &&
    grep -Fqx -- "$expected_acme_bin" "$runner" 2>/dev/null &&
    grep -Fqx -- "$expected_acme_home" "$runner" 2>/dev/null &&
    grep -Fqx -- "$expected_cert_file" "$runner" 2>/dev/null &&
    grep -Fqx -- "$expected_state_file" "$runner" 2>/dev/null &&
    grep -Fqx -- "$expected_identity_file" "$runner" 2>/dev/null &&
    grep -Fqx -- "$expected_lock_file" "$runner" 2>/dev/null &&
    grep -Fqx -- "  1) [[ \${1-} == --force ]] || exit 2; force=1 ;;" "$runner" 2>/dev/null &&
    grep -Fqx -- '  *) exit 2 ;;' "$runner" 2>/dev/null &&
    grep -Fqx -- 'exec 9> "$lock_file" || exit 1' "$runner" 2>/dev/null &&
    grep -Fqx -- 'if ! flock -n 9; then' "$runner" 2>/dev/null &&
    grep -Fqx -- "  acme_identity=\$(read_runner_acme_identity) || exit 1" "$runner" 2>/dev/null &&
    grep -Fqx -- 'state_read_epoch=$(date +%s) || exit 1' "$runner" 2>/dev/null &&
    grep -Fqx -- '  if [[ -n $previous_renewal ]] && ((previous_renewal <= state_read_epoch)); then' "$runner" 2>/dev/null &&
    grep -Fqx -- "$expected_cron_command" "$runner" 2>/dev/null &&
    grep -Fqx -- "$expected_force_command" "$runner" 2>/dev/null &&
    grep -Fqx -- "before_fingerprint=\$(certificate_fingerprint || true)" "$runner" 2>/dev/null &&
    grep -Fqx -- "after_fingerprint=\$(certificate_fingerprint || true)" "$runner" 2>/dev/null &&
    grep -Fqx -- "state_tmp=\$(mktemp \"\$state_dir/.acme_renew.state.XXXXXX\") || exit 1" "$runner" 2>/dev/null &&
    grep -Fq -- "mv -fT -- \"\$state_tmp\" \"\$state_file\"" "$runner" 2>/dev/null &&
    bash -n "$runner" >/dev/null 2>&1
}

write_acme_renew_runner(){
  local runner state identity runner_tmp
  runner=$(acme_renew_runner_path)
  state=$(acme_renew_state_path)
  identity=$(acme_renew_runner_identity)
  if acme_renew_runner_is_current; then
    return 0
  fi
  runner_tmp=$(mktemp "$STATE_DIR/.acme_renew.XXXXXX") || return 1
  if ! {
    printf '%s\n' '#!/bin/bash' "$identity" 'set -u' 'umask 077'
    printf 'state_dir=%q\n' "$STATE_DIR"
    printf 'acme_bin=%q\n' "$ACME_BIN"
    printf 'acme_home=%q\n' "$ACME_HOME"
    printf 'cert_file=%q\n' "${ACME_CERT:-$STATE_DIR/fullchain.pem}"
    printf 'state_file=%q\n' "$state"
    printf 'identity_file=%q\n' "$ACME_IDENTITY"
    printf 'lock_file=%q\n' "$(acme_lock_path)"
    cat <<'ACMERENEW'

certificate_fingerprint(){
  local fingerprint
  [[ -s $cert_file ]] || return 1
  fingerprint=$(sha256sum "$cert_file" 2>/dev/null | awk '{print $1}') || return 1
  [[ $fingerprint =~ ^[0-9a-fA-F]{64}$ ]] || return 1
  printf '%s\n' "${fingerprint,,}"
}

valid_acme_identity(){
  local name=$1 label
  local -a labels
  [[ ${#name} -le 253 && $name == *.* && $name != .* && $name != *. ]] || return 1
  IFS='.' read -r -a labels <<< "$name"
  for label in "${labels[@]}"; do
    [[ ${#label} -ge 1 && ${#label} -le 63 ]] || return 1
    [[ $label =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?$ ]] || return 1
  done
}

read_runner_acme_identity(){
  local identity
  local -a identity_lines=()
  [[ -f $identity_file && ! -L $identity_file ]] || return 1
  mapfile -t identity_lines < "$identity_file" || return 1
  [[ ${#identity_lines[@]} -eq 1 ]] || return 1
  identity=${identity_lines[0]}
  valid_acme_identity "$identity" || return 1
  printf '%s\n' "$identity"
}

force=0
case $# in
  0) ;;
  1) [[ ${1-} == --force ]] || exit 2; force=1 ;;
  *) exit 2 ;;
esac
if [[ -e $lock_file || -L $lock_file ]]; then
  [[ -f $lock_file && ! -L $lock_file ]] || exit 1
fi
exec 9> "$lock_file" || exit 1
if ! chmod 600 "$lock_file"; then
  exec 9>&-
  exit 1
fi
if ! flock -n 9; then
  exec 9>&-
  exit 75
fi
if ((force)); then
  acme_identity=$(read_runner_acme_identity) || exit 1
fi

last_renewal_epoch=0
state_read_epoch=$(date +%s) || exit 1
if [[ -f $state_file && ! -L $state_file ]]; then
  previous_renewal=$(awk -F= '$1 == "last_renewal_epoch" && $2 ~ /^[0-9]+$/ &&
    length($2) <= 12 && ($2 == "0" || $2 !~ /^0/) { print $2; exit }' "$state_file" 2>/dev/null)
  if [[ -n $previous_renewal ]] && ((previous_renewal <= state_read_epoch)); then
    last_renewal_epoch=$previous_renewal
  fi
fi

before_fingerprint=$(certificate_fingerprint || true)
if ((force)); then
  HOME="$state_dir" "$acme_bin" --home "$acme_home" --config-home "$acme_home" --renew -d "$acme_identity" --ecc --force
else
  HOME="$state_dir" "$acme_bin" --cron --home "$acme_home" --config-home "$acme_home"
fi
exit_code=$?
after_fingerprint=$(certificate_fingerprint || true)
check_epoch=$(date +%s)

if [[ -n $after_fingerprint && $before_fingerprint != "$after_fingerprint" ]]; then
  last_renewal_epoch=$check_epoch
fi

if ((exit_code != 0)); then
  result=failed
elif [[ -z $after_fingerprint ]]; then
  result=failed
  exit_code=1
elif [[ $before_fingerprint != "$after_fingerprint" ]]; then
  result=renewed
else
  result=unchanged
fi

state_tmp=$(mktemp "$state_dir/.acme_renew.state.XXXXXX") || exit 1
trap 'rm -f -- "$state_tmp"' EXIT
trap 'exit 1' HUP INT TERM
if ! printf '%s\n' \
  "last_check_epoch=$check_epoch" \
  "last_result=$result" \
  "last_exit_code=$exit_code" \
  "last_renewal_epoch=$last_renewal_epoch" \
  "cert_fingerprint=$after_fingerprint" > "$state_tmp" ||
   ! chmod 600 "$state_tmp" ||
   ! mv -fT -- "$state_tmp" "$state_file"; then
  exit 1
fi
trap - EXIT HUP INT TERM
exit "$exit_code"
ACMERENEW
  } > "$runner_tmp" || ! chmod 700 "$runner_tmp" || ! mv -fT -- "$runner_tmp" "$runner"; then
    rm -f "$runner_tmp"
    return 1
  fi
  acme_renew_runner_is_current
}

remove_acme_renew_artifacts(){
  local runner state
  runner=$(acme_renew_runner_path)
  state=$(acme_renew_state_path)
  rm -f "$runner" "$state"
}

acme_renew_artifacts_exist(){
  local runner state
  runner=$(acme_renew_runner_path)
  state=$(acme_renew_state_path)
  [[ -e $runner || -L $runner || -e $state || -L $state ]]
}

remove_acme_renew_cron(){
  local current filtered
  load_current_crontab || return 1
  current=$CURRENT_CRONTAB
  if ! crontab_has_acme_entries "$current"; then
    remove_acme_renew_artifacts
    return
  fi
  filtered=$(printf '%s\n' "$current" | filter_acme_cron_entries || true)
  printf '%s\n' "$filtered" | crontab - >/dev/null 2>&1 || return 1
  load_current_crontab || return 1
  if crontab_has_acme_entries "$CURRENT_CRONTAB"; then
    return 1
  fi
  remove_acme_renew_artifacts
}

setup_acme_renew_cron(){
  local current filtered entry identity
  if ! cron_daemon_is_active; then
    red "cron/crond 服务未运行，拒绝写入无法执行的 ACME 续期任务"
    return 1
  fi
  if ! identity=$(valid_acme_renewal_identity 2>/dev/null); then
    identity=$(recover_acme_renewal_identity 2>/dev/null) || {
      red "ACME 身份、证书或域名配置校验失败，无法修复自动续期"
      return 1
    }
  fi
  dns_provider_credentials_present || return 1
  write_acme_reload_hook || return 1
  if ! managed_acme_live_layout_is_valid ||
     ! acme_deployment_config_is_current "$identity"; then
    yellow "正在把 ACME 证书迁移到原子部署模式……"
    register_acme_certificate_deployment "$identity" 0 || return 1
  fi
  identity=$(valid_acme_renewal_identity 2>/dev/null) || return 1
  acme_deployment_config_is_current "$identity" || return 1
  write_acme_renew_runner || return 1
  load_current_crontab || return 1
  current=$CURRENT_CRONTAB
  filtered=$(printf '%s\n' "$current" | filter_acme_cron_entries || true)
  entry=$(acme_renew_cron_entry)
  { printf '%s\n' "$filtered"; printf '%s\n' "$entry"; } | crontab - >/dev/null 2>&1 || return 1
  load_current_crontab || return 1
  acme_renew_runner_is_current && acme_renew_cron_is_current "$CURRENT_CRONTAB"
}

ensure_acme_renew_cron(){
  if acme_renew_artifacts_exist; then
    setup_acme_renew_cron
  else
    return 0
  fi
}
# acme-nginx-module: 90-main
# Command-line entry (no interactive panel)
usage(){
  cat <<'USAGE'
用法: acme-nginx <命令>

命令:
  install       安装固定版本 acme.sh，并生成 /etc/acme-nginx.conf 配置模板
  issue         读取配置并首次签发证书（已有有效证书时提示使用 renew/force-renew）
  renew         续期检查（cron 使用；证书变化后自动 reload nginx）
  force-renew   强制重新签发当前证书并 reload nginx
  status        显示证书与自动续期状态
  uninstall     移除 cron、续期检查器、证书与状态（含配置文件）
  -h|--help     显示本帮助
USAGE
}

cmd_install(){
  if ! core_dependencies_ready; then
    red "缺少必要命令，请先安装依赖（awk curl flock jq openssl crontab 等）"
    return 1
  fi
  prepare_state_dir || { red "初始化状态目录失败：$STATE_DIR"; return 1; }
  if ! config_is_present; then
    write_config_template || { red "生成配置模板失败"; return 1; }
    yellow "已生成配置模板：$CONFIG_FILE"
    yellow "请填写 DNS_PROVIDER、DOMAIN 与对应供应商凭据后运行 acme-nginx issue"
  else
    load_config || { red "配置文件格式或权限异常：$CONFIG_FILE"; return 1; }
    blue "配置文件校验通过：供应商 ${DNS_PROVIDER:-cloudflare}，主域名 $ACME_PRIMARY_DOMAIN"
    [[ -n $ACME_WILDCARD_DOMAIN ]] && blue "同时申请泛域名：$ACME_WILDCARD_DOMAIN"
  fi
  install_official_acme || return 1
  green "acme.sh v${ACME_VERSION} 安装完成"
}

cmd_issue(){
  if ! core_dependencies_ready; then
    red "缺少必要命令，请先安装依赖"
    return 1
  fi
  if ! config_is_present || ! load_config; then
    red "配置文件缺失或无效：$CONFIG_FILE（先运行 acme-nginx install 生成模板）"
    return 1
  fi
  prepare_state_dir || { red "初始化状态目录失败：$STATE_DIR"; return 1; }
  if identity=$(read_acme_identity 2>/dev/null) &&
     load_certificate_metadata "$ACME_CERT" "$ACME_KEY" 2>/dev/null &&
     [[ $CERT_META_STATE == valid ]] &&
     certificate_identity_matches "$ACME_CERT" "$identity"; then
    yellow "已存在有效证书（$identity），无需重复签发；如需重签请运行 acme-nginx force-renew"
    return 0
  fi
  if ! with_acme_lock issue_certificate; then
    return 1
  fi
  if ! with_acme_lock setup_acme_renew_cron; then
    yellow "证书已签发，但自动续期任务设置失败，请检查 root crontab 与 cron 服务"
  else
    green "自动续期任务已安装（每天 03:17 / 09:17 / 15:17 / 21:17 检查）"
  fi
  green "签发完成。Nginx 可引用："
  printf '  ssl_certificate     %s;\n' "$ACME_CERT"
  printf '  ssl_certificate_key %s;\n' "$ACME_KEY"
}

cmd_renew(){
  if ! core_dependencies_ready; then
    red "缺少必要命令，请先安装依赖"
    return 1
  fi
  if ! config_is_present || ! load_config; then
    red "配置文件缺失或无效：$CONFIG_FILE"
    return 1
  fi
  prepare_state_dir || { red "初始化状态目录失败：$STATE_DIR"; return 1; }
  if ! with_acme_lock setup_acme_renew_cron; then
    red "自动续期组件修复失败，无法执行检查"
    return 1
  fi
  local runner
  runner=$(acme_renew_runner_path) || return 1
  green "正在执行 ACME 续期检查；未到计划时间时不会重复签发……"
  if "$runner"; then
    green "续期检查完成"
  else
    red "续期检查失败，请查看上方 acme.sh 输出"
    return 1
  fi
}

nginx_running(){
  if command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]; then
    systemctl is-active --quiet nginx
  elif command -v rc-service >/dev/null 2>&1; then
    rc-service nginx status >/dev/null 2>&1
  else
    return 1
  fi
}

cmd_force_renew(){
  if ! core_dependencies_ready; then
    red "缺少必要命令，请先安装依赖"
    return 1
  fi
  if ! config_is_present || ! load_config; then
    red "配置文件缺失或无效：$CONFIG_FILE"
    return 1
  fi
  prepare_state_dir || { red "初始化状态目录失败：$STATE_DIR"; return 1; }
  if ! with_acme_lock setup_acme_renew_cron; then
    red "自动续期组件修复失败，无法执行强制重签"
    return 1
  fi
  local runner
  runner=$(acme_renew_runner_path) || return 1
  yellow "强制重签会立即联系 Let's Encrypt，并计入证书签发频率限制"
  green "正在强制重新签发当前证书……"
  if ! "$runner" --force; then
    red "强制重签失败，请查看上方 acme.sh 输出"
    return 1
  fi
  if ! load_acme_renew_state || [[ $ACME_RENEW_LAST_RESULT != renewed ]]; then
    red "重签命令已结束，但托管证书没有发生变化，不能确认重签成功"
    return 1
  fi
  if nginx_running; then
    green "证书已重新签发，nginx 已通过回调 reload 并加载新证书"
  else
    yellow "证书已重新签发；nginx 当前未运行，下次启动时会加载新证书"
  fi
}

inspect_acme_renewal_health(){
  local current state now identity reference_epoch
  ACME_RENEW_HEALTH=normal
  ACME_RENEW_HEALTH_DETAIL=正常
  local plugin
  if ! plugin=$(dns_provider_plugin_file) ||
     [[ ! -x $ACME_BIN || ! -f $ACME_HOME/dnsapi/$plugin || ! -s $ACME_IDENTITY ]]; then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="acme.sh 组件不完整"
  elif ! dns_provider_credentials_present; then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="DNS 供应商凭据缺失或格式异常"
  elif ! identity=$(read_acme_identity 2>/dev/null); then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="ACME 身份文件损坏"
  elif ! load_certificate_metadata "$ACME_CERT" "$ACME_KEY" ||
       [[ $CERT_META_STATE != valid ]] ||
       ! certificate_identity_matches "$ACME_CERT" "$identity"; then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="当前证书无效或未覆盖 ACME 身份"
  elif ! load_acme_certificate_schedule "$identity"; then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="ACME 域名配置或续期时间记录异常"
  elif ! managed_acme_live_layout_is_valid; then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="证书原子部署目录或 current 指针异常"
  elif ! acme_deployment_config_is_current "$identity"; then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="acme.sh 部署目标不是受管暂存目录"
  elif ! cron_daemon_is_active; then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="cron/crond 未运行"
  elif ! acme_reload_hook_is_current; then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="证书生效回调缺失或过期"
  elif ! acme_renew_runner_is_current; then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="续期检查器缺失或过期"
  elif ! load_current_crontab; then
    ACME_RENEW_HEALTH=error
    ACME_RENEW_HEALTH_DETAIL="无法读取 root crontab"
  else
    current=$CURRENT_CRONTAB
    if ! acme_renew_cron_is_current "$current"; then
      ACME_RENEW_HEALTH=error
      ACME_RENEW_HEALTH_DETAIL="定时任务缺失或不规范"
    fi
  fi
  if [[ $ACME_RENEW_HEALTH == normal ]]; then
    state=$(acme_renew_state_path)
    if load_acme_renew_state; then
      now=$(date +%s 2>/dev/null || true)
      if [[ $ACME_RENEW_LAST_RESULT == failed ]]; then
        ACME_RENEW_HEALTH=error
        ACME_RENEW_HEALTH_DETAIL="最近一次检查失败，退出码 $ACME_RENEW_LAST_EXIT_CODE"
      elif [[ $now =~ ^[0-9]+$ ]] && ((now - ACME_RENEW_LAST_CHECK_EPOCH > 86400)); then
        ACME_RENEW_HEALTH=error
        ACME_RENEW_HEALTH_DETAIL="超过 24 小时没有成功检查"
      elif [[ $now =~ ^[0-9]+$ ]] && ((ACME_RENEW_LAST_CHECK_EPOCH > now + 300)); then
        ACME_RENEW_HEALTH=error
        ACME_RENEW_HEALTH_DETAIL="最近检查时间晚于系统时间"
      fi
    elif [[ -e $state || -L $state ]]; then
      ACME_RENEW_HEALTH=error
      ACME_RENEW_HEALTH_DETAIL="续期状态记录损坏或权限异常"
    else
      now=$(date +%s 2>/dev/null || true)
      reference_epoch=${ACME_META_DEPLOYED_EPOCH:-$ACME_META_CREATED_EPOCH}
      if [[ $now =~ ^[0-9]+$ && $reference_epoch =~ ^[0-9]+$ ]] &&
         ((now - reference_epoch > 28800)); then
        ACME_RENEW_HEALTH=error
        ACME_RENEW_HEALTH_DETAIL="证书部署超过 8 小时但没有续期检查记录"
      fi
    fi
  fi
}

cmd_status(){
  local identity
  if ! identity=$(read_acme_identity 2>/dev/null); then
    red "尚未找到 ACME 身份，证书可能未签发"
    return 1
  fi
  show_certificate_metadata "Let's Encrypt (acme-nginx)" "$ACME_CERT" "$ACME_KEY" "$identity"
  show_acme_certificate_schedule "$identity" || true
  printf 'Nginx 引用路径: %s / %s\n' "$ACME_CERT" "$ACME_KEY"
  printf '定时检查: 每天 03:17 / 09:17 / 15:17 / 21:17（服务器时间）\n'
  inspect_acme_renewal_health
  if [[ $ACME_RENEW_HEALTH == normal ]]; then
    green "自动续期: 正常"
  else
    red "自动续期: 异常（$ACME_RENEW_HEALTH_DETAIL）"
  fi
  if load_acme_renew_state; then
    printf '最近自动检查: %s\n' "$ACME_RENEW_LAST_CHECK"
    case $ACME_RENEW_LAST_RESULT in
      renewed) green "最近检查结果: 已续期并执行证书生效回调" ;;
      unchanged) green "最近检查结果: 成功，暂不需要续期" ;;
      failed) red "最近检查结果: 失败（退出码 $ACME_RENEW_LAST_EXIT_CODE）" ;;
    esac
    if [[ $ACME_RENEW_LAST_RENEWAL_EPOCH != 0 ]]; then
      printf '最近自动续期: %s\n' "$ACME_RENEW_LAST_RENEWAL"
    fi
  else
    if [[ -e $(acme_renew_state_path) || -L $(acme_renew_state_path) ]]; then
      red "最近自动检查: 状态记录损坏或权限异常"
    else
      yellow "最近自动检查: 暂无记录"
    fi
  fi
  if nginx_running; then
    green "续期生效方式: 成功续期后自动 reload nginx"
  else
    yellow "续期生效方式: nginx 当前未运行，续期不会强制启动"
  fi
}

cmd_uninstall(){
  if ! with_acme_lock remove_acme_renew_cron; then
    red "移除续期定时任务失败"
    return 1
  fi
  local path failed=0
  for path in "$ACME_LIVE" "$ACME_HOME" "$ACME_CERT" "$ACME_KEY" \
              "$ACME_IDENTITY" "$ACME_RELOAD" "$STATE_DIR" "$CONFIG_FILE"; do
    if [[ -e $path || -L $path ]]; then
      rm -rf -- "$path" || failed=1
    fi
  done
  if [[ $failed -eq 0 ]]; then
    green "acme-nginx 已卸载：cron、证书、状态与配置均已移除"
  else
    red "卸载不完整，请手动检查 $STATE_DIR 与 $CONFIG_FILE"
    return 1
  fi
}

main(){
  case ${1-} in
    install) shift; cmd_install ;;
    issue) shift; cmd_issue ;;
    renew) shift; cmd_renew ;;
    force-renew) shift; cmd_force_renew ;;
    status) shift; cmd_status ;;
    uninstall) shift; cmd_uninstall ;;
    -h|--help|help) usage ;;
    -V|--version) printf 'acme-nginx %s\n' "$acme_nginx_version" ;;
    *) usage >&2; exit 2 ;;
  esac
}

# acme-nginx-entrypoint
main "$@"
