#!/usr/bin/env bash
set -Eeuo pipefail

export LC_ALL=C
umask 022

ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
readonly ROOT_DIR
readonly SRC_DIR="$ROOT_DIR/src"
readonly OUTPUT="$ROOT_DIR/acme-nginx.sh"
readonly VERSION_FILE="$ROOT_DIR/VERSION"
readonly TEMP_ROOT="${TMPDIR:-/tmp}"
readonly GENERATED_NOTICE="# Generated by scripts/build.sh from src/; do not edit acme-nginx.sh directly."
readonly GENERATED_MARKER="# acme-nginx-generated-artifact: v1"
readonly ENTRYPOINT_MARKER="# acme-nginx-entrypoint"

readonly -a MODULES=(
  "00-bootstrap.sh"
  "10-acme.sh"
  "60-cron.sh"
  "90-main.sh"
)

mode=build
candidate=
hook_candidate=

cleanup(){
  [[ -z $candidate ]] || rm -f -- "$candidate"
  [[ -z $hook_candidate ]] || rm -f -- "$hook_candidate"
}
trap cleanup EXIT

fail(){
  printf 'build: %s\n' "$1" >&2
  exit 1
}

usage(){
  printf 'Usage: %s [--check]\n' "${0##*/}"
}

case ${1-} in
  "") ;;
  --check) mode=check ;;
  -h|--help) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
esac
[[ $# -le 1 ]] || { usage >&2; exit 2; }

for command_name in awk bash cat chmod cmp grep head iconv mktemp mv od sed \
  sha256sum sort tail tr uniq; do
  command -v "$command_name" >/dev/null 2>&1 || fail "missing command: $command_name"
done

[[ -d $SRC_DIR && ! -L $SRC_DIR ]] || fail "src must be a real directory"
[[ -f $VERSION_FILE && ! -L $VERSION_FILE ]] || fail "VERSION must be a regular file"
[[ -d $TEMP_ROOT && -w $TEMP_ROOT ]] || fail "temporary directory is not writable: $TEMP_ROOT"

version=$(<"$VERSION_FILE")
[[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "VERSION must contain one semantic version"

shopt -s nullglob
actual_modules=("$SRC_DIR"/*.sh)
[[ ${#actual_modules[@]} -eq ${#MODULES[@]} ]] ||
  fail "src module set does not match the build manifest"

for index in "${!MODULES[@]}"; do
  module_name=${MODULES[$index]}
  module_path="$SRC_DIR/$module_name"
  actual_name=${actual_modules[$index]##*/}
  [[ $actual_name == "$module_name" ]] ||
    fail "unexpected module order or name: $actual_name"
  [[ -f $module_path && ! -L $module_path && -s $module_path ]] ||
    fail "$module_name must be a non-empty regular file"

  iconv -f UTF-8 -t UTF-8 "$module_path" >/dev/null 2>&1 ||
    fail "$module_name is not valid UTF-8"
  first_bytes=$(head -c 3 "$module_path" | od -An -t x1 | tr -d '[:space:]')
  [[ $first_bytes != efbbbf ]] || fail "$module_name contains a UTF-8 BOM"
  ! grep -q $'\r' "$module_path" || fail "$module_name contains CR characters"
  ! od -An -t x1 "$module_path" | grep -Eq '(^|[[:space:]])00([[:space:]]|$)' ||
    fail "$module_name contains a NUL byte"
  last_byte=$(tail -c 1 "$module_path" | od -An -t x1 | tr -d '[:space:]')
  [[ $last_byte == 0a ]] || fail "$module_name must end with LF"

  module_id=${module_name%.sh}
  module_marker="# acme-nginx-module: $module_id"
  if [[ $index -eq 0 ]]; then
    [[ $(sed -n '1p' "$module_path") == '#!/bin/bash' ]] ||
      fail "$module_name must start with #!/bin/bash"
    [[ $(sed -n '2p' "$module_path") == "$GENERATED_NOTICE" ]] ||
      fail "$module_name has an invalid generated notice"
    [[ $(sed -n '3p' "$module_path") == "$GENERATED_MARKER" ]] ||
      fail "$module_name has an invalid generated marker"
    [[ $(sed -n '4p' "$module_path") == "$module_marker" ]] ||
      fail "$module_name has an invalid module marker"
  else
    [[ $(sed -n '1p' "$module_path") == "$module_marker" ]] ||
      fail "$module_name has an invalid module marker"
  fi
  [[ $(grep -Fxc -- "$module_marker" "$module_path" || true) -eq 1 ]] ||
    fail "$module_name must contain exactly one module marker"
  entrypoint_count=$(grep -Fxc -- "$ENTRYPOINT_MARKER" "$module_path" || true)
  if [[ $index -eq $((${#MODULES[@]} - 1)) ]]; then
    [[ $entrypoint_count -eq 1 ]] || fail "$module_name must contain the entrypoint"
  else
    [[ $entrypoint_count -eq 0 ]] || fail "$module_name must not contain the entrypoint"
  fi
  bash -n "$module_path" || fail "$module_name failed bash -n"
done

if [[ -e $OUTPUT || -L $OUTPUT ]]; then
  [[ -f $OUTPUT && ! -L $OUTPUT ]] || fail "acme-nginx.sh must be a regular non-symlink file"
fi

if [[ $mode == check ]]; then
  candidate=$(mktemp "$TEMP_ROOT/sb-build.XXXXXX") || fail "cannot create build candidate"
else
  candidate=$(mktemp "$ROOT_DIR/.acme-nginx.sh.XXXXXX") || fail "cannot create build candidate"
fi
for module_name in "${MODULES[@]}"; do
  cat -- "$SRC_DIR/$module_name" >> "$candidate"
done

[[ $(sed -n '1p' "$candidate") == '#!/bin/bash' ]] || fail "candidate shebang is invalid"
[[ $(grep -Fxc -- "$GENERATED_NOTICE" "$candidate" || true) -eq 1 ]] ||
  fail "candidate generated notice is invalid"
[[ $(grep -Fxc -- "$GENERATED_MARKER" "$candidate" || true) -eq 1 ]] ||
  fail "candidate generated marker is invalid"
[[ $(grep -Fxc -- "$ENTRYPOINT_MARKER" "$candidate" || true) -eq 1 ]] ||
  fail "candidate entrypoint marker is invalid"

mapfile -t built_markers < <(grep -E '^# acme-nginx-module: [0-9]{2}-[a-z0-9-]+$' "$candidate")
[[ ${#built_markers[@]} -eq ${#MODULES[@]} ]] || fail "candidate module markers are incomplete"
for index in "${!MODULES[@]}"; do
  expected_marker="# acme-nginx-module: ${MODULES[$index]%.sh}"
  [[ ${built_markers[$index]} == "$expected_marker" ]] || fail "candidate module order is invalid"
done

! grep -Eq '^[[:space:]]*(source[[:space:]]+|\.[[:space:]]+)' "$candidate" ||
  fail "runtime module loading is forbidden"

duplicate_functions=$(sed -n 's/^\([A-Za-z_][A-Za-z0-9_]*\)()[[:space:]]*{.*/\1/p' "$candidate" |
  sort | uniq -d)
[[ -z $duplicate_functions ]] || fail "duplicate function definitions: $duplicate_functions"

[[ $(grep -Fxc -- "acme_nginx_version=\"v$version\"" "$candidate" || true) -eq 1 ]] ||
  fail "VERSION and sb_version do not match"
bash -n "$candidate" || fail "generated acme-nginx.sh failed bash -n"

[[ $(grep -Fxc -- 'ACMERELOAD' "$candidate" || true) -eq 1 ]] ||
  fail "ACME reload heredoc terminator is invalid"
hook_candidate=$(mktemp "$TEMP_ROOT/sb-acme-reload.XXXXXX") || fail "cannot create hook candidate"
awk '/<<'\''ACMERELOAD'\''/{inside=1; next} /^ACMERELOAD$/{inside=0} inside' \
  "$candidate" > "$hook_candidate"
[[ -s $hook_candidate ]] || fail "ACME reload hook extraction failed"
bash -n "$hook_candidate" || fail "ACME reload hook failed bash -n"

if [[ $mode == check ]]; then
  [[ -f $OUTPUT && ! -L $OUTPUT ]] || fail "acme-nginx.sh is missing"
  cmp -s "$candidate" "$OUTPUT" || fail "acme-nginx.sh is out of date; run scripts/build.sh"
  digest=$(sha256sum "$OUTPUT" | awk '{print $1}')
  printf 'build check passed: %s\n' "$digest"
  exit 0
fi

chmod 755 "$candidate" || fail "cannot set executable mode on build candidate"
if [[ -f $OUTPUT ]] && cmp -s "$candidate" "$OUTPUT"; then
  rm -f -- "$candidate"
  candidate=
else
  mv -fT -- "$candidate" "$OUTPUT" || fail "cannot replace acme-nginx.sh"
  candidate=
fi

digest=$(sha256sum "$OUTPUT" | awk '{print $1}')
printf 'built acme-nginx.sh: %s\n' "$digest"
