#!/bin/bash
# Generated by scripts/build.sh from src/; do not edit acme-nginx.sh directly.
# acme-nginx-generated-artifact: v1
# acme-nginx-module: 00-bootstrap
export LANG=en_US.UTF-8
umask 077

ACME_VERSION="3.1.4"
ACME_ARCHIVE_SHA256="e5f8e187bbf5251e0cd8891f2622daab9850366bd17bea9f92c2fe2ee091fd32"
STATE_DIR="/etc/acme-nginx"
CONFIG_FILE="/etc/acme-nginx.conf"
ACME_HOME="$STATE_DIR/acme"
ACME_BIN="$ACME_HOME/acme.sh"
ACME_STAGE="$ACME_HOME/stage"
ACME_STAGE_CERT="$ACME_STAGE/fullchain.pem"
ACME_STAGE_KEY="$ACME_STAGE/private.key"
ACME_LIVE="$STATE_DIR/live"
ACME_GENERATIONS="$ACME_LIVE/generations"
ACME_CURRENT="$ACME_LIVE/current"
ACME_CERT="$STATE_DIR/fullchain.pem"
ACME_KEY="$STATE_DIR/privkey.pem"
ACME_IDENTITY="$STATE_DIR/identity"
ACME_RELOAD="$STATE_DIR/reload.sh"
ACME_LOCK="/run/acme-nginx.lock"
ACME_RENEW_RUNNER="$STATE_DIR/renew.sh"
ACME_RENEW_STATE="$STATE_DIR/renew.state"
ACME_RELOAD_IDENTITY="# acme-nginx-reload-v1"
ACME_RENEW_IDENTITY="# acme-nginx-renew-v1"
ACME_CRON_MARKER="# acme-nginx-managed"
ACME_LOCK_FD=
ACME_LOCK_HELD=0
ACME_PRIMARY_DOMAIN=
ACME_WILDCARD_DOMAIN=
CF_ACCOUNT_ID=
CF_TOKEN=

# shellcheck disable=SC2034
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;36m'
bblue='\033[0;34m'
plain='\033[0m'
red(){ echo -e "\033[31m\033[01m$1\033[0m";}
green(){ echo -e "\033[32m\033[01m$1\033[0m";}
yellow(){ echo -e "\033[33m\033[01m$1\033[0m";}
blue(){ echo -e "\033[36m\033[01m$1\033[0m";}
white(){ echo -e "\033[37m\033[01m$1\033[0m";}
if [[ $EUID -ne 0 ]]; then
  yellow "请以root模式运行 acme-nginx"
  exit 1
fi

acme_nginx_version="v0.1.0"

valid_ipv4(){
  local ip=$1 IFS=. octets octet
  [[ $ip =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  read -r -a octets <<< "$ip"
  for octet in "${octets[@]}"; do
    ((10#$octet <= 255)) || return 1
  done
}

valid_ipv6(){
  local ip=$1 group nonempty=0
  local -a groups
  [[ -n $ip && ${#ip} -le 39 && $ip == *:* && $ip =~ ^[0-9A-Fa-f:]+$ ]] || return 1
  [[ $ip != ':' && $ip != '::' && $ip != '::1' && $ip != *:::* ]] || return 1
  [[ ! $ip =~ ^[Ff][Ee][89AaBb] && ! $ip =~ ^[Ff][CcDd] ]] || return 1
  if [[ $ip == *::* ]]; then
    [[ ${ip#*::} != *::* ]] || return 1
  fi
  IFS=':' read -r -a groups <<< "$ip"
  for group in "${groups[@]}"; do
    [[ -z $group ]] && continue
    [[ ${#group} -le 4 && $group =~ ^[0-9A-Fa-f]+$ ]] || return 1
    nonempty=$((nonempty + 1))
  done
  if [[ $ip == *::* ]]; then
    ((nonempty < 8))
  else
    ((nonempty == 8))
  fi
}

sanitize_location(){
  tr '\r\n\t' '   ' | sed 's/[[:cntrl:]]//g; s/[[:space:]][[:space:]]*/ /g; s/^ //; s/ $//' | cut -c1-160
}

valid_hostname(){
  local name=$1 label
  local -a labels
  [[ ${#name} -le 253 && $name == *.* && $name != .* && $name != *. ]] || return 1
  IFS='.' read -r -a labels <<< "$name"
  for label in "${labels[@]}"; do
    [[ ${#label} -ge 1 && ${#label} -le 63 ]] || return 1
    [[ $label =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?$ ]] || return 1
  done
}

core_dependencies_ready(){
  local cmd
  for cmd in awk bash cat chmod cmp cp curl cut date flock grep iconv jq mkdir \
    mktemp mv od openssl sed sha256sum sort tail tr uniq crontab; do
    command -v "$cmd" >/dev/null 2>&1 || return 1
  done
}

cron_daemon_is_active(){
  if command -v apk >/dev/null 2>&1; then
    rc-service crond status >/dev/null 2>&1
  else
    systemctl is-active --quiet cron 2>/dev/null ||
      systemctl is-active --quiet crond 2>/dev/null
  fi
}


prepare_state_dir(){
  local path
  for path in "$STATE_DIR" "$ACME_HOME" "$ACME_STAGE"; do
    if [[ -e $path || -L $path ]]; then
      [[ -d $path && ! -L $path ]] || return 1
    else
      mkdir -p "$path" || return 1
    fi
    chmod 700 "$path" || return 1
  done
  if [[ -e $ACME_LIVE || -L $ACME_LIVE ]]; then
    [[ -d $ACME_LIVE && ! -L $ACME_LIVE ]] || return 1
  else
    mkdir "$ACME_LIVE" || return 1
    chmod 700 "$ACME_LIVE" || return 1
  fi
  if [[ -e $ACME_GENERATIONS || -L $ACME_GENERATIONS ]]; then
    [[ -d $ACME_GENERATIONS && ! -L $ACME_GENERATIONS ]] || return 1
  else
    mkdir "$ACME_GENERATIONS" || return 1
    chmod 700 "$ACME_GENERATIONS" || return 1
  fi
}

config_mode_is_private(){
  local mode
  mode=$(stat -c '%a' "$CONFIG_FILE" 2>/dev/null || true)
  case $(uname -s 2>/dev/null) in
    MINGW*|MSYS*) return 0 ;;
    *) [[ $mode == 600 ]] ;;
  esac
}

config_is_present(){
  [[ -f $CONFIG_FILE && ! -L $CONFIG_FILE ]] || return 1
  config_mode_is_private
}

write_config_template(){
  if [[ -e $CONFIG_FILE || -L $CONFIG_FILE ]]; then
    [[ -f $CONFIG_FILE && ! -L $CONFIG_FILE ]] || return 1
    return 0
  fi
  local tmp
  tmp=$(mktemp "$STATE_DIR/.acme-nginx.conf.XXXXXX") || return 1
  if ! {
    printf '%s\n' '# acme-nginx 配置文件'
    printf '%s\n' '# Cloudflare API 凭据（Account ID 为 32 位十六进制）'
    printf '%s\n' 'CF_ACCOUNT_ID='
    printf '%s\n' 'CF_TOKEN='
    printf '%s\n' '# 主域名（必填）'
    printf '%s\n' 'DOMAIN='
    printf '%s\n' '# 是否同时申请泛域名证书：1 表示同时签 *.DOMAIN'
    printf '%s\n' 'WILDCARD=0'
  } > "$tmp" || ! chmod 600 "$tmp" || ! mv -fT -- "$tmp" "$CONFIG_FILE"; then
    rm -f "$tmp"
    return 1
  fi
}

load_config(){
  local line key value
  local account_count=0 token_count=0 domain_count=0 wildcard_count=0
  local account='' token='' domain='' wildcard=''
  [[ -f $CONFIG_FILE && ! -L $CONFIG_FILE ]] || return 1
  config_mode_is_private || return 1
  while IFS= read -r line || [[ -n $line ]]; do
    [[ -n $line ]] || continue
    [[ $line == \#* ]] && continue
    [[ $line == *=* ]] || return 1
    key=${line%%=*}
    value=${line#*=}
    [[ -n $value && $value != *"'"* && $value != *$'\r'* ]] || return 1
    case $key in
      CF_ACCOUNT_ID)
        account_count=$((account_count + 1))
        account=$value
        ;;
      CF_TOKEN)
        token_count=$((token_count + 1))
        token=$value
        ;;
      DOMAIN)
        domain_count=$((domain_count + 1))
        domain=$value
        ;;
      WILDCARD)
        wildcard_count=$((wildcard_count + 1))
        wildcard=$value
        ;;
      *) return 1 ;;
    esac
  done < "$CONFIG_FILE"
  [[ $account_count -eq 1 && $token_count -eq 1 &&
     $domain_count -eq 1 && $wildcard_count -eq 1 ]] || return 1
  valid_cloudflare_account_id "$account" || return 1
  [[ $token =~ ^[A-Za-z0-9_-]{10,200}$ ]] || return 1
  [[ $wildcard == 0 || $wildcard == 1 ]] || return 1
  normalize_acme_domain "$domain" || return 1
  if [[ $wildcard == 1 ]]; then
    ACME_WILDCARD_DOMAIN="*.$ACME_PRIMARY_DOMAIN"
  else
    ACME_WILDCARD_DOMAIN=
  fi
  CF_ACCOUNT_ID=$account
  CF_TOKEN=$token
}
